
[[jkube-controller]]
==== jkube-controller

This enricher is used to ensure that a controller is present.
This can be either directly configured with fragments or with the {plugin-configuration-type} configuration.
An explicit configuration always takes precedence over auto detection.
See https://kubernetes.io/docs/concepts/workloads/controllers/[Kubernetes doc] for more information on types of controllers.

The following configuration parameters can be used to influence the behaviour of this enricher:

[[enricher-jkube-controller]]
.Default controller enricher
[cols="1,6,1"]
|===
| Element | Description | Property

| *name*
| Name of the Controller. Kubernetes Controller names must start with a letter. If the maven artifactId starts with a
  digit, `s` will be prefixed.

ifeval::["{plugin-type}" == "maven"]
  Defaults to `${project.artifactId}`.
endif::[]

ifeval::["{plugin-type}" == "gradle"]
  Defaults to project name.
endif::[]
| `jkube.enricher.jkube-controller.name`

| *pullPolicy*
| Image pull policy to use for the container. One of: _IfNotPresent_, _Always_.

  Defaults to `IfNotPresent`.
| `jkube.enricher.jkube-controller.pullPolicy`

| *type*
| Type of Controller to create. One of: _ReplicationController_, _ReplicaSet_, _Deployment_, _DeploymentConfig_,
  _StatefulSet_, _DaemonSet_, _Job_.

  Defaults to `Deployment`.
| `jkube.enricher.jkube-controller.type`

| *replicaCount*
| Number of replicas for the container.

  Defaults to `1`.
| `jkube.enricher.jkube-controller.replicaCount`
|===
