
[[oc:log]]
== *oc:log*

This goal tails the log of the app that you deployed via the <<oc:deploy>> goal

[source, sh]
----
mvn oc:log
----

You can then terminate the output by hitting `Ctrl+C`

If you wish to get the log of the app and then terminate immediately then try:

[source, sh]
----
mvn oc:log -Djkube.log.follow=false
----

This lets you pipe the output into grep or some other tool

[source, sh]
----
mvn oc:log -Djkube.log.follow=false | grep Exception
----

If your app is running in multiple pods you can configure the pod name to log via the `jkube.log.pod` property, otherwise it defaults to the latest pod:

[source, sh]
----
mvn oc:log -Djkube.log.pod=foo
----

If your pod has multiple containers you can configure the container name to log via the `jkube.log.container` property, otherwise it defaults to the first container:

[source, sh]
----
mvn oc:log -Djkube.log.container=foo
----

[[Supported-Properties-Log]]
=== Supported Properties for Log goal

.Options available with log goal
[cols="1.6.3"]
|===
| Element | Description | Property(System property or Maven property)

| *logFollow*
| Get follow logs for your application inside Kubernetes. Defaults to `true`
| `jkube.log.follow`

| *logContainer*
| Get logs of some specific container inside your application Deployment. Defaults to `null`
| `jkube.log.container`

| *logPod*
| Get logs of some specific pod inside your application Deployment. Defaults to `null`
| `jkube.log.pod`
|===
