
[[oc:watch]]
== *oc:watch*

This goal is used to monitor the project workspace for changes and automatically trigger a redeploy of the application
running on Kubernetes.

In order to use oc:watch for spring-boot, you need to make sure that `devtools` is included in the repacked
archive, as shown in the following listing:
----
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<excludeDevtools>false</excludeDevtools>
			</configuration>
		</plugin>
----

Then you need to set a `spring.devtools.remote.secret` in application.properties, as shown in the following example:

----
spring.devtools.remote.secret=mysecret
----

Before entering the watch mode, this goal must generate the docker image and the Kubernetes resources
(optionally including some development libraries/configuration),
and deploy the app on Kubernetes. Lifecycle bindings should be configured as follows to allow
the generation of such resources.

.Lifecycle bindings for oc:watch
[source, xml, indent=0]
----
<plugin>
  <groupId>io.jkube</groupId>
  <artifactId>oc-maven-plugin</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

For any application having `resource` and `build` goals bound to the lifecycle, the following
command can be used to run the watch task.

[source, bash]
----
mvn oc:watch
----

This plugin supports different watcher providers, enabled automatically if the project satisfies certain conditions.

Watcher providers can also be configured manually. The <<generator-example,Generator example>> is a good blueprint, simply replace `<generator>` with `<watcher>`. The configuration is structurally identical.

[[watcher-spring-boot]]
=== Spring Boot

This watcher is enabled by default for all Spring Boot projects. It performs the following actions:

* deploys your application with Spring Boot DevTools enabled
* tails the log of the latest running pod for your application
* watches the local development build of your Spring Boot based application and then triggers a reload of the application when there are changes

You can try it on any spring boot application via:

[source, sh]
----
mvn oc:watch
----

Once the goal starts up the spring boot RemoteSpringApplication it will watch for local development changes.

e.g. if you edit the java code of your app and then build it via something like this:

[source, sh]
----
mvn package
----

You should see your app reload on the fly in the shell running the <<oc:watch>> goal!

There is also support for LiveReload as well.


[[watcher-docker-image]]
=== Docker Image

This is a generic watcher that can be used in Kubernetes mode only. Once activated, it listens for changes in the project workspace
 in order to trigger a redeploy of the application.

The watcher can be activated e.g. by running this command in another shell:

[source, sh]
----
mvn package
----

The watcher will detect that the binary artifact has changed and will first rebuild the docker image,
then start a redeploy of the Kubernetes pod.

It uses the watch feature of the https://dmp.jkube.io/#docker:watch[docker-maven-plugin] under the hood.
