
[[jkube-configmap-file]]
==== jkube-configmap-file

This enricher adds ConfigMap defined as `resources` in plugin configuration and/or resolves file content from an annotation.

As XML you can define:

[source, xml]
.pom.xml
----
<configuration>
  <resources>
    <configMap>
      <name>myconfigmap</name>
      <entries>
        <entry>
          <name>A</name>
          <value>B</value>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
----

This creates a ConfigMap data with key `A` and value `B`.

You can also use `file` tag to refer to the content of a file.

[source, xml]
----
<configuration>
  <resources>
    <configMap>
      <name>configmap-test</name>
      <entries>
        <entry>
          <file>src/test/resources/test-application.properties</file>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
----

This creates a ConfigMap with key `test-application.properties` and value the content of the `src/test/resources/test-application.properties` file.
If you set `name` tag then this is used as key instead of the filename.

[[configmap-xml-configuration]]
===== ConfigMap XML Configuration
Here are the supported options while providing `<configMap>` in XML configuration

.XML configmap configuration`<configMap>`
[cols="1,5"]
|===
| Element | Description

| <<configmap-entry-xml-configuration, `entries`>>
| data for ConfigMap

| `name`
| Name of the ConfigMap
|===

[[configmap-entry-xml-configuration]]
===== ConfigMap Entry XML Configuration
`<entries>` is a list of `<port>` configuration objects. Here are the supported options while providing `<entry>` in XML configuration

.XML configmap entry configuration`<entry>`
[cols="1,5"]
|===
| Element | Description

| `value`
| Entry value

| `file`
| path to a file or directory. If it's a single file then file contents would be read as value. If it's a directory then each file's content is stored as value with file name as key.

| `name`
| Entry name
|===

If you are defining a custom `ConfigMap` file, you can use an annotation to define a file name as key and its content as the value:

[source, yaml]
----
metadata:
  name: ${project.artifactId}
  annotations:
    jkube.eclipse.org/cm/application.properties: src/test/resources/test-application.properties
----

This creates a `ConfigMap` data with key `application.properties` (part defined after `cm`) and value the content of `src/test/resources/test-application.properties` file. 

You can specify a directory instead of a file:

[source, yaml]
----
metadata:
  name: ${project.artifactId}
  annotations:
    jkube.eclipse.org/cm/application.properties: src/test/resources/test-dir
----

This creates a `ConfigMap` named `application.properties` (part defined after `cm`) and for each file under the directory `test-dir` one entry with file name as key and its content as the value; subdirectories are ignored.
