
[[jkube-configmap-file]]
==== jkube-configmap-file

This enricher adds ConfigMap defined as `resources` in plugin configuration and/or resolves file content from an annotation.

As XML you can define:

[source, xml]
.pom.xml
----
<configuration>
  <resources>
    <configMap>
      <name>myconfigmap</name>
      <entries>
        <entry>
          <name>A</name>
          <value>B</value>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
----

This creates a ConfigMap data with key `A` and value `B`.

You can also use `file` tag to refer to the content of a file.

[source, xml]
----
<configuration>
  <resources>
    <configMap>
      <name>configmap-test</name>
      <entries>
        <entry>
          <file>src/test/resources/test-application.properties</file>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
----

This creates a ConfigMap with key `test-application.properties` and value the content of the `src/test/resources/test-application.properties` file.
If you set `name` tag then this is used as key instead of the filename.

If you are defining a custom `ConfigMap` file, you can use an annotation to define a file name as key and its content as the value:

[source, yaml]
----
metadata:
  name: ${project.artifactId}
  annotations:
    maven.jkube.io/cm/application.properties: src/test/resources/test-application.properties
----

This creates a `ConfigMap` data with key `application.properties` (part defined after `cm`) and value the content of `src/test/resources/test-application.properties` file.
