
[[jkube-healthcheck-vertx]]
==== jkube-healthcheck-vertx

This enricher adds kubernetes readiness and liveness probes with Eclipse Vert.x applications.
The readiness probe lets Kubernetes detect when the application is ready, while the liveness probe allows Kubernetes to
verify that the application is still alive.

This enricher allows configuring the readiness and liveness probes. The following probe types are supported:
`http` (emit HTTP requests), `tcp` (open a socket), `exec` (execute a command).

By default, this enricher uses the same configuration for liveness and readiness probes. But specific configurations can
be provided too. The configurations can be overridden using project's properties.

===== Using the jkube-healthcheck-vertx enricher

The enricher is automatically executed if your project uses the `vertx-maven-plugin` or depends on `io.vertx:vertx-core`.
However, by default, no health check will be added to your deployment unless configured explicitly.

===== Minimal configuration

The minimal configuration to add health checks is the following:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>{plugin}</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>jkube</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-vertx>
                  <path>/health</path>
              </jkube-healthcheck-vertx>
            </config>
          </enricher>
        </configuration>
      </plugin>
----

It configures the readiness and liveness health checks using HTTP requests on the port `8080` (default port) and on the
path `/health`. The defaults are:

* port = `8080` (for HTTP)
* scheme = `HTTP`
* path = _none_ (disabled)

the previous configuration can also be given use project's properties:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <properties>
        <vertx.health.path>/health</vertx.health.path>
    </properties>
----

===== Configuring differently the readiness and liveness health checks

You can provide two different configuration for the readiness and liveness checks:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>{plugin}</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>jkube</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-vertx>
                  <readiness>
                    <path>/ready</path>
                  </readiness>
                  <liveness>
                    <path>/health</path>
                  </liveness>
              </jkube-healthcheck-vertx>
            </config>
          </enricher>
        </configuration>
      </plugin>
----

You can also use the `readiness` and `liveness` chunks in user properties:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <properties>
        <vertx.health.readiness.path>/ready</vertx.health.readiness.path>
        <vertx.health.liveness.path>/ready</vertx.health.liveness.path>
    </properties>
----

Shared (generic) configuration can be set outside of the specific configuration. For instance, to use the port 8081:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>{plugin}</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>jkube</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-vertx>
                  <port>8081</port>
                  <readiness>
                    <path>/ready</path>
                  </readiness>
                  <liveness>
                    <path>/health</path>
                  </liveness>
              </jkube-healthcheck-vertx>
            </config>
          </enricher>
        </configuration>
      </plugin>
----

Or:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <properties>
        <vertx.health.port>8081</vertx.health.port>
        <vertx.health.readiness.path>/ready</vertx.health.readiness.path>
        <vertx.health.liveness.path>/ready</vertx.health.liveness.path>
    </properties>
----

===== Configuration Structure

The configuration is structured as follows

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <!-- Generic configuration, applied to both liveness and readiness -->
            <path>/both</path>
            <liveness>
                <!-- Specific configuration for the liveness probe -->
                <port-name>ping</port-name>
            </liveness>
            <readiness>
                <!-- Specific configuration for the readiness probe -->
                <port-name>ready</port-name>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

The same structure is used in project's properties:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
  <properties>
    <!-- Generic configuration given as vertx.health.$attribute -->
    <vertx.health.path>/both</vertx.health.path>
    <!-- Specific liveness configuration given as vertx.health.liveness.$attribute -->
    <vertx.health.liveness.port-name>ping</vertx.health.liveness.port-name>
    <!-- Specific readiness configuration given as vertx.health.readiness.$attribute -->
    <vertx.health.readiness.port-name>ready</vertx.health.readiness.port-name>
  </properties>
----

**Important**: Project's plugin configuration override the project's properties.
The overriding rules are:
_specific configuration_ > _specific properties_ > _generic configuration_ > _generic properties_.

===== Probe configuration

You can configure the different aspects of the probes. These attributes can be configured for both the readiness and
liveness probes or be specific to one.


.Vert.x HealthCheck Enricher probe configuration
[cols="1,5,2"]
|===
| Element | Description | Property

|*type*
|The probe type among `http` (default), `tcp` and `exec`.

 Defaults to `http`.
| `vertx.health.type`

  `jkube.enricher.jkube-healthcheck-vertx.type`

|*initial-delay*
|Number of seconds after the container has started before probes are initiated.
| `vertx.health.initial-delay`

  `jkube.enricher.jkube-healthcheck-vertx.initial-delay`


|*period*
|How often (in seconds) to perform the probe.
| `vertx.health.period`

  `jkube.enricher.jkube-healthcheck-vertx.period`


|*timeout*
|Number of seconds after which the probe times out.
| `vertx.health.timeout`

  `jkube.enricher.jkube-healthcheck-vertx.timeout`


|*success-threshold*
|Minimum consecutive successes for the probe to be considered successful after having failed.
| `vertx.health.success-threshold`

  `jkube.enricher.jkube-healthcheck-vertx.success-threshold`


|*failure-threshold*
|Minimum consecutive failures for the probe to be considered failed after having succeeded.
| `vertx.health.failure-threshold`

  `jkube.enricher.jkube-healthcheck-vertx.failure-threshold`

|===


More details about probes are available on https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/.

===== HTTP specific probe configuration

When using HTTP `GET` requests to determine readiness or liveness, several aspects can be configured. HTTP probes are used by default. To be more specific set the `type` attribute to `http`.

.Vert.x HealthCheck Enricher HTTP probe configuration
[cols="1,5,2"]
|===
| Element | Description | Property

| *scheme*
| Scheme to use for connecting to the host.

  Defaults to `HTTP`.

| `vertx.health.scheme`

  `jkube.enricher.jkube-healthcheck-vertx.scheme`

| *path*
| Path to access on the HTTP server. An empty path disable the check.
| `vertx.health.path`

  `jkube.enricher.jkube-healthcheck-vertx.path`

| *headers*
| Custom headers to set in the request. HTTP allows repeated headers. It cannot be configured using project's properties.
  An example is available below.
| `vertx.health.headers`

  `jkube.enricher.jkube-healthcheck-vertx.headers`


| *port*
| Port number to access the container. A 0 or negative number disables the check.

  Defaults to `8080`.
| `vertx.health.port`

  `jkube.enricher.jkube-healthcheck-vertx.port`

| *port-name*
| Name of the port to access on the container. If neither the `port` nor the `port-name` is set, the check is disabled.
  If both are set the configuration is considered invalid.
| `vertx.health.port-name`

  `jkube.enricher.jkube-healthcheck-vertx.port-name`

|===

Here is an example of HTTP probe configuration:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <initialDelay>3</initialDelay>
            <period>3</period>
            <liveness>
                <port>8081</port>
                <path>/ping</path>
                <scheme>HTTPS</scheme>
                <headers>
                    <X-Custom-Header>Awesome</X-Custom-Header>
                </headers>
            </liveness>
            <readiness>
                <!-- disable the readiness probe -->
                <port>-1</port>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

===== TCP specific probe configuration

You can also configure the probes to just open a socket on a specific port. The `type` attribute must be set to `tcp`.

.Vert.x HealthCheck Enricher TCP probe configuration
[cols="1,5,2"]
|===
| Element | Description | Property

| *port*
| Port number to access the container. A 0 or negative number disables the check.
| `vertx.health.port`

  `jkube.enricher.jkube-healthcheck-vertx.port`

| `port-name`
| Name of the port to access on the container. If neither the `port` nor the `port-name` is set, the check is disabled.
  If both are set the configuration is considered invalid.
| `vertx.health.port-name`

  `jkube.enricher.jkube-healthcheck-vertx.port-name`

|===

For example:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <initialDelay>3</initialDelay>
            <period>3</period>
            <liveness>
                <type>tcp</type>
                <port>8081</port>
            </liveness>
            <readiness>
                <!-- use HTTP Get probe -->
                <path>/ping</path>
                <port>8080</port>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

===== Exec probe configuration

You can also configure the probes to execute a command. If the command succeeds, it returns 0, and Kubernetes consider the pod to be alive and healthy. If the command returns a non-zero value, Kubernetes kills the pod and restarts it. To use a command, you must set the `type` attribute to `exec`:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <initialDelay>3</initialDelay>
            <period>3</period>
            <liveness>
                <type>exec</type>
                <command>
                    <cmd>cat</cmd>
                    <cmd>/tmp/healthy</cmd>
                </command>
            </liveness>
            <readiness>
                <-- use HTTP Get probe -->
                <path>/ping</path>
                <port>8080</port>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

As you can see in the snippet above the command is passed using the `command` attribute. This attribute cannot be
configured using project's properties. An empty command disables the check.

===== Disabling health checks

You can disable the checks by setting:

* the `port` to 0 or to a negative number for `http` and `tcp` probes
* the `command` to an empty list for `exec`

In the first case, you can use project's properties to disable them:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <!-- Disables `tcp` and `http` probes -->
    <vertx.health.port>-1</vertx.health.port>
----

For `http` probes, an empty or not set `path` also disable the probe.
