#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        app: namespace
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube
      name: namespace-to-create-and-operate
    status:
      phase: Active
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        jkube.io/git-commit: "@ignore@"
        prometheus.io/scrape: "true"
        jkube.io/git-branch: "@ignore@"
        prometheus.io/port: "9779"
      labels:
        expose: "true"
        app: namespace
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube
      name: namespace
      namespace: namespace-to-create-and-operate
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: namespace
        provider: jkube
        group: org.eclipse.jkube
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        jkube.io/git-commit: "@ignore@"
        jkube.io/git-branch: "@ignore@"
      labels:
        provider: jkube
        app: namespace
        version: "@ignore@"
        group: org.eclipse.jkube
      name: namespace
      namespace: namespace-to-create-and-operate
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: namespace
          provider: jkube
          group: org.eclipse.jkube
      template:
        metadata:
          annotations:
            jkube.io/git-commit: "@ignore@"
            jkube.io/git-branch: "@ignore@"
          labels:
            provider: jkube
            app: namespace
            version: "@ignore@"
            group: org.eclipse.jkube
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: "@matches('jkube/namespace:.*$')@"
              imagePullPolicy: IfNotPresent
              name: spring-boot
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                - containerPort: 9779
                  name: prometheus
                  protocol: TCP
                - containerPort: 8778
                  name: jolokia
                  protocol: TCP
              securityContext:
                privileged: false