---
apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-url: "@ignore@"
      app.openshift.io/vcs-ref: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: groovy-dsl-resource-requests-limits
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: groovy-dsl-resource-requests-limits
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: groovy-dsl-resource-requests-limits
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-url: "@ignore@"
          app.openshift.io/vcs-ref: "@ignore@"
          app.openshift.io/vcs-uri: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: groovy-dsl-resource-requests-limits
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
        name: groovy-dsl-resource-requests-limits
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: groovy-dsl-resource-requests-limits:latest
          imagePullPolicy: IfNotPresent
          name: orgeclipsejkubeintegrationtestsgradle-groovy-dsl-resource-requests-limits
          securityContext:
            privileged: false
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 250m
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - orgeclipsejkubeintegrationtestsgradle-groovy-dsl-resource-requests-limits
        from:
          kind: ImageStreamTag
          name: groovy-dsl-resource-requests-limits:latest
      type: ImageChange
