---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: controller-name-fragment
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: customized-name
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: controller-name-fragment
          provider: jkube
          group: org.eclipse.jkube.integration.tests.gradle
      template:
        metadata:
          annotations:
            jkube.eclipse.org/git-url: "@ignore@"
            jkube.eclipse.org/git-commit: "@ignore@"
            jkube.eclipse.org/git-branch: "@ignore@"
          labels:
            app: controller-name-fragment
            provider: jkube
            version: "@ignore@"
            group: org.eclipse.jkube.integration.tests.gradle
        spec:
          containers:
            - env:
                - name: ADDITIONAL_VARIABLE
                  value: additional-value
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: repository/controller-name-fragment:latest
              imagePullPolicy: IfNotPresent
              name: repository-controller-name-fragment
              securityContext:
                privileged: false
