---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "9779"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-url: "@ignore@"
      app.openshift.io/vcs-ref: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: spring-boot-managementhealthprobes
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: spring-boot-managementhealthprobes
      app.kubernetes.io/version: "@ignore@"
    name: spring-boot-managementhealthprobes
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-managementhealthprobes
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/name: spring-boot-managementhealthprobes
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/managed-by: jkube
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-url: "@ignore@"
      app.openshift.io/vcs-ref: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: spring-boot-managementhealthprobes
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: spring-boot-managementhealthprobes
      app.kubernetes.io/version: "@ignore@"
    name: spring-boot-managementhealthprobes
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: spring-boot-managementhealthprobes
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/name: spring-boot-managementhealthprobes
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/managed-by: jkube
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-url: "@ignore@"
          app.openshift.io/vcs-ref: "@ignore@"
          app.openshift.io/vcs-uri: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: spring-boot-managementhealthprobes
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
          app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
          app.kubernetes.io/managed-by: jkube
          app.kubernetes.io/name: spring-boot-managementhealthprobes
          app.kubernetes.io/version: "@ignore@"
        name: spring-boot-managementhealthprobes
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: spring-boot-managementhealthprobes:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: spring-boot-managementhealthprobes:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-url: "@ignore@"
      app.openshift.io/vcs-ref: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: spring-boot-managementhealthprobes
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: spring-boot-managementhealthprobes
      app.kubernetes.io/version: "@ignore@"
    name: spring-boot-managementhealthprobes
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: spring-boot-managementhealthprobes
