---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      expose: "true"
      app: groovy-dsl-image
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: groovy-dsl-image
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: groovy-dsl-image
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: groovy-dsl-image
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: groovy-dsl-image
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: groovy-dsl-image
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.io/git-url: "@ignore@"
          jkube.io/git-commit: "@ignore@"
          jkube.io/git-branch: "@ignore@"
        labels:
          app: groovy-dsl-image
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: repository/groovy-dsl-image-test:latest
          imagePullPolicy: IfNotPresent
          name: repository-groovy-dsl-image
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          securityContext:
            privileged: false
