apiVersion: networking.k8s.io/v1
metadata:
  name: ${k8sgroupId}-${project.artifactId}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - ${proj.hostname}
    secretName: letsencrypt-${k8sgroupId}-${project.artifactId}
  rules:
  - host: ${proj.hostname}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ${k8sgroupId}-${project.artifactId}-service
              port: 
                number: ${tomee.port}