

[[enrichers]]
= Enrichers

Enriching is the complementary concept to <<generators, Generators>>. Whereas Generators are used to create and customize Docker images, Enrichers are use to create and customize Kubernetes resource objects.

There are a lot of similarities to Generators:

* Each Enricher has a unique name.
* Enrichers are looked up automatically from the plugin dependencies and there is a set of default enrichers delivered with this plugin.
* Enrichers are configured the same ways as generators

The <<generator-example,Generator example>> is a good blueprint, simply replace `<generator>` with `<enricher>`. The configuration is structural identical:

.Enricher configuration
[cols="2,6"]
|===
| Element | Description

| `<includes>`
| Contains one ore more `<include>` elements with enricher names which should be included. If given, only this list of enrichers are included in this order. The enrichers from every active profile are included, too. However the enrichers listed here are moved to the front of the list, so that they are called first. Use the profile `raw` if you want to explicitly set the complete list of enrichers.

| `<excludes>`
| Holds one or more `<exclude>` elements with enricher names to exclude. This means all the detected enrichers are used except the ones mentioned in this section.

| `<config>`
| Configuration for all enrichers. Each enricher supports a specific set of configuration values as described in its documentation. The subelements of this section are enricher names. E.g. for enricher `jkube-service`, the sub-element is called `<jkube-service>`. This element then holds the specific enricher configuration like `<name>` for the service name. Configuration coming from profiles are merged into this config, but not overriding the configuration specified here.
|===

This plugin comes with a set of default enrichers. In addition custom enrichers can be easily added by providing implementation of the <<enricher-api, Enricher API>> and adding these as a dependency to the build.

[[enrichers-default]]
== Default Enrichers

kubernetes-maven-plugin comes with a set of enrichers which are enabled by default. There are two categories of default enrichers:

* *Generic Enrichers* are used to add default resource object when they are missing or add common metadata extracted from the given build information
* *Specific Enrichers* are enrichers which are focused on a certain tech stack that they detect.

. Default Enrichers Overview
[cols="2,7"]
|===
| Enricher | Description

| <<jkube-prometheus>>
| Add Prometheus annotations.

| <<jkube-maven-scm-enricher>>
| Add Maven SCM information as annotations to the kubernetes/openshift resources

| <<jkube-controller>>
| Create default controller (replication controller, replica set or deployment) if missing.

| <<jkube-dependency>>
| Examine build dependencies for `kubernetes.yml` and add the objects found therein.

| <<jkube-git>>
| Check local `.git` directory and add build information as annotations.

| <<jkube-image>>
| Add the image name into a `PodSpec` of replication controller, replication sets and deployments, if missing.

| <<jkube-name>>
| Add a default name to every object which misses a name.

| <<jkube-pod-annotation>>
| Copy over annotations from a `Deployment` to a `Pod`

| <<jkube-portname>>
| Add a default portname for commonly known service.

| <<jkube-project-label>>
| Add Maven coordinates as labels to all objects.

| <<jkube-service>>
| Create a default service if missing and extract ports from the Docker image configuration.

| <<jkube-maven-issue-mgmt-enricher>>
| Add Maven Issue Management information as annotations to the kubernetes/openshift resources

| <<jkube-revision-history-enricher>>
| Add revision history limit (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit[Kubernetes doc]) as a deployment spec property to the Kubernetes/OpenShift resources.

| <<jkube-triggers-annotation>>
| Add ImageStreamTag change triggers on Kubernetes resources such as StatefulSets, ReplicaSets and DaemonSets using the `image.openshift.io/triggers` annotation.

| <<jkube-configmap-file>>
| Add ConfigMap elements defined as XML or as annotation.

| <<jkube-secret-file>>
| Add Secret elements defined as annotation.

| <<jkube-jkube-serviceaccount>>
| Add a ServiceAccount defined as XML or mentioned in resource fragement.
|===

[[enrichers-standard]]
=== Standard Enrichers

Default enrichers are used for adding missing resources or adding metadata to given resource objects. The following default enhancers are available out of the box

[[jkube-controller]]
==== jkube-controller

include::enricher/_jkube_service.adoc[]

[[jkube-image]]
==== jkube-image

[[jkube-name]]
==== jkube-name

[[jkube-portname]]
==== jkube-portname

[[jkube-pod-annotation]]
==== jkube-pod-annotation

[[jkube-project-label]]
==== jkube-project-label

Enricher that adds standard labels and selectors to generated resources (e.g. `app`, `group`, `provider`, `version`).

The `jkube-project-label` enricher supports the following configuration options:

[cols="2,6,3"]
|===
| Option | Description | Default

| `useProjectLabel`
| Enable this flag to turn on the generation of the old `project` label in Kubernetes resources. The `project` label has been replaced by the `app` label in newer versions of the plugin.
| `false`
|===

The project labels which are already specified in the input fragments are not overridden by the enricher.

[[jkube-git]]
==== jkube-git

Enricher that adds info from .git directory as annotations.

The git branch & latest commit on the branch are annotated as jkube.git-branch & jkube.git-commit.
fabrci8/git-url is annotated as the url of your configured remote.

[cols="2,6,3"]
|===
| Option | Description | Default

| `gitRemote`
| Configures the git remote name, whose url you want to annotate as 'git-url'.
| `origin`
|===

[[jkube-dependency]]
==== jkube-dependency

[[jkube-volume-permission]]
==== jkube-volume-permission

Enricher which fixes the permission of persistent volume mount with the help of an init container.

[[jkube-autotls]]
==== jkube-openshift-autotls

Enricher which adds appropriate annotations and volumes to enable OpenShift's automatic https://docs.openshift.org/latest/dev_guide/secrets.html#service-serving-certificate-secrets[Service Serving Certificate Secrets].
This enricher adds an init container to convert the service serving certificates from PEM (the format that OpenShift generates them in) to
a JKS-format Java keystore ready for consumption in Java services.

This enricher is disabled by default. In order to use it, you must configure the Kubernetes Maven plugin to use this enricher:

[source,xml]
----
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>{version}</version>
  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <enricher>
      <includes>
        <include>jkube-openshift-autotls</include>
      </includes>
      <config>
        <jkube-openshift-autotls>
          ...
        </jkube-openshift-autotls>
      </config>
    </enricher>
  </configuration>
</plugin>
----

The auto-TLS enricher supports the following configuration options:

[cols="2,6,3"]
|===
| Option | Description | Default

| `tlsSecretName`
| The name of the secret to be used to store the generated service serving certs.
| `<project.artifactId>-tls`

| `tlsSecretVolumeMountPoint`
| Where the service serving secret should be mounted to in the pod.
| `/var/run/secrets/jkube.io/tls-pem`

| `tlsSecretVolumeName`
| The name of the secret volume.
| `tls-pem`

| `jksVolumeMountPoint`
| Where the generated keystore volume should be mounted to in the pod.
| `/var/run/secrets/jkube.io/tls-jks`

| `jksVolumeName`
| The name of the keystore volume.
| `tls-jks`

| `pemToJKSInitContainerImage`
| The name of the image used as an init container to convert PEM certificate/key to Java keystore.
| `jimmidyson/pemtokeystore:v0.1.0`

| `pemToJKSInitContainerName`
| the name of the init container to convert PEM certificate/key to Java keystore.
| `tls-jks-converter`

| `keystoreFileName`
| The name of the generated keystore file.
| `keystore.jks`

| `keystorePassword`
| The password to use for the generated keystore.
| `changeit`

| `keystoreCertAlias`
| The alias in the keystore used for the imported service serving certificate.
| `server`
|===

[[enrichers-jkube]
=== JKube Enrichers
JKube enrichers are used for providing the connection to other components of the jkube.Microservices platform. They are useful to add icons to application or links to documentation sites.

[[jkube-healthcheck-karaf]]
==== jkube-healthcheck-karaf

This enricher adds kubernetes readiness and liveness probes with Apache Karaf. This requires that
 `jkube.karaf-checks` has been enabled in the Karaf startup features.

The enricher will use the following settings by default:

- port = `8181`
- scheme = `HTTP`
- failureThreshold = `3`
- successThreshold = `1`

and use paths `/readiness-check` for readiness check and `/health-check` for liveness check.

These options cannot be configured.

[[jkube-prometheus]]
==== jkube-prometheus

This enricher adds Prometheus annotation like:

[source,yaml]
----
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: 9779
----

By default the enricher inspects the images' BuildConfiguration and add the annotations if the port 9779 is listed.
You can force the plugin to add annotations by setting enricher's config ```prometheusPort```

[[jkube-healthcheck-webapp]]
==== jkube-healthcheck-webapp

This enricher adds kubernetes readiness and liveness probes with WebApp. This requires that you have `maven-war-plugin` set.

The enricher will use the following settings by default:

- port = `8080`
- scheme = `HTTP`
- path = ``
- initialReadinessDelay = 10
- initialLivenessDelay = 180

If `path` attribute is not set (default value) then this enricher is disabled.

These values can be configured by the enricher in the `kubernetes-maven-plugin` configuration as shown below:

[source,xml]
----
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>{version}</version>
  <executions>
    <execution>
      <id>fmp</id>
        <goals>
          <goal>resource</goal>
          <goal>helm</goal>
          <goal>build</goal>
        </goals>
    </execution>
  </executions>
  <configuration>
    <enricher>
      <config>
        <jkube-healthcheck-webapp>
          <path>/</path>
        </jkube-healthcheck-webapp>
      </config>
    </enricher>
  </configuration>
    ...
</plugin>
----

[[jkube-healthcheck-spring-boot]]
==== jkube-healthcheck-spring-boot

This enricher adds kubernetes readiness and liveness probes with Spring Boot. This requires the following dependency
 has been enabled in Spring Boot

[source,xml]
   <dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-actuator</artifactId>
   </dependency>

The enricher will try to discover the settings from the `application.properties` / `application.yaml` Spring Boot configuration file.

The port number is read from the `management.port` option, and will use the default value of `8080`
The scheme will use HTTPS if `server.ssl.key-store` option is in use, and fallback to use `HTTP` otherwise.

The enricher will use the following settings by default:

* `readinessProbeInitialDelaySeconds` : `10`
* `readinessProbePeriodSeconds` : _<kubernetes-default>_
* `livenessProbeInitialDelaySeconds` : `180`
* `livenessProbePeriodSeconds` : _<kubernetes-default>_
* `timeoutSeconds` : _<kubernetes-default>_
* `failureThreshold`: `3`
* `successThreshold`: `1`

These values can be configured by the enricher in the `kubernetes-maven-plugin` configuration as shown below:
[source,xml]
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-spring-boot>
                <timeoutSeconds>5</timeoutSeconds>
                <readinessProbeInitialDelaySeconds>30</readinessProbeInitialDelaySeconds>
                <failureThreshold>3</failureThreshold>
                <successThreshold>1</successThreshold>
              </jkube-healthcheck-spring-boot>
            </config>
          </enricher>
        </configuration>
      </plugin>



[[jkube-healthcheck-wildfly-swarm]]
==== jkube-jkube-healthcheck-wildfly-swarm

This enricher adds kubernetes readiness and liveness probes with WildFly Swarm. This requires the following fraction
 has been enabled in WildFly Swarm

[source,xml]
   <dependency>
     <groupId>org.wildfly.swarm</groupId>
     <artifactId>microprofile-health</artifactId>
   </dependency>

The enricher will use the following settings by default:

- port = `8080`
- scheme = `HTTP`
- path = `/health`
- failureThreshold = `3`
- successThreshold = `1`

These values can be configured by the enricher in the `kubernetes-maven-plugin` configuration as shown below:
[source,xml]
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-wildfly-swarm>
                <port>4444</port>
                <scheme>HTTPS</scheme>
                <path>health/myapp</path>
                <failureThreshold>3</failureThreshold>
                <successThreshold>1</successThreshold>
              </jkube-healthcheck-wildfly-swarm>
            </config>
          </enricher>
        </configuration>
      </plugin>


[[jkube-healthcheck-thorntail-v2]]
==== jkube-healthcheck-thorntail-v2

This enricher adds kubernetes readiness and liveness probes with Thorntail v2. This requires the following fraction
 has been enabled in Thorntail

[source,xml]
   <dependency>
     <groupId>io.thorntail</groupId>
     <artifactId>microprofile-health</artifactId>
   </dependency>

The enricher will use the following settings by default:

- port = `8080`
- scheme = `HTTP`
- path = `/health`
- failureThreshold = `3`
- successThreshold = `1`

These values can be configured by the enricher in the `kubernetes-maven-plugin` configuration as shown below:
[source,xml]
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-thorntail>
                <port>4444</port>
                <scheme>HTTPS</scheme>
                <path>health/myapp</path>
                <failureThreshold>3</failureThreshold>
                <successThreshold>1</successThreshold>
              </jkube-healthcheck-thorntail>
            </config>
          </enricher>
        </configuration>
      </plugin>

[[jkube-healthcheck-vertx]]
==== jkube-healthcheck-vertx

This enricher adds kubernetes readiness and liveness probes with Eclipse Vert.x applications. The readiness probe lets Kubernetes
detects when the application is ready, while the liveness probe allows Kubernetes to verify that the application is
still alive.

This enricher allows configuring the readiness and liveness probes. Are supported: `http` (emit HTTP requests), `tcp` (open a socket), `exec` (execute a command).

By default, this enricher uses the same configuration for liveness and readiness probes. But specific configurations can be provided. The configurations can be overridden using project's properties.

===== Using the jkube-healthcheck-vertx enricher

The enricher is automatically executed if your project uses the `vertx-maven-plugin` or depends on `io.vertx:vertx-core`.
However, by default, no health check will be added to your deployment.

===== Minimal configuration

The minimal configuration to add health checks is the following:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-vertx>
                  <path>/health</path>
              </jkube-healthcheck-vertx>
            </config>
          </enricher>
        </configuration>
      </plugin>
----

It configures the readiness and liveness health checks using HTTP requests on the port `8080` (default port) and on the path `/health`. The defaults are:

* port = `8080` (for HTTP)
* scheme = `HTTP`
* path = _none_ (disabled)

the previous configuration can also be given use project's properties:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <properties>
        <vertx.health.path>/health</vertx.health.path>
    </properties>
----

===== Configuring differently the readiness and liveness health checks

You can provide two different configuration for the readiness and liveness checks:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-vertx>
                  <readiness>
                    <path>/ready</path>
                  </readiness>
                  <liveness>
                    <path>/health</path>
                  </liveness>
              </jkube-healthcheck-vertx>
            </config>
          </enricher>
        </configuration>
      </plugin>
----

You can also use the `readiness` and `liveness` chunks in user properties:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <properties>
        <vertx.health.readiness.path>/ready</vertx.health.readiness.path>
        <vertx.health.liveness.path>/ready</vertx.health.liveness.path>
    </properties>
----

Shared (generic) configuration can be set outside of the specific configuration. For instance, to use the port 8081:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>{version}</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <jkube-healthcheck-vertx>
                  <port>8081</port>
                  <readiness>
                    <path>/ready</path>
                  </readiness>
                  <liveness>
                    <path>/health</path>
                  </liveness>
              </jkube-healthcheck-vertx>
            </config>
          </enricher>
        </configuration>
      </plugin>
----

Or:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <properties>
        <vertx.health.port>8081</vertx.health.port>
        <vertx.health.readiness.path>/ready</vertx.health.readiness.path>
        <vertx.health.liveness.path>/ready</vertx.health.liveness.path>
    </properties>
----

===== Configuration Structure

The configuration is structured as follows

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <!-- Generic configuration, applied to both liveness and readiness -->
            <path>/both</path>
            <liveness>
                <!-- Specific configuration for the liveness probe -->
                <port-name>ping</port-name>
            </liveness>
            <readiness>
                <!-- Specific configuration for the readiness probe -->
                <port-name>ready</port-name>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

The same structured is used in project's properties:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <!-- Generic configuration given as vertx.health.$attribute -->
    <vertx.health.path>/both</vertx.health.path>
    <!-- Specific liveness configuration given as vertx.health.liveness.$attribute -->
    <vertx.health.liveness.port-name>ping</vertx.health.liveness.port-name>
    <!-- Specific readiness configuration given as vertx.health.readiness.$attribute -->
    <vertx.health.readiness.port-name>ready</vertx.health.readiness.port-name>
----

**Important**: Project's properties override the configuration provided in the plugin configuration. The overriding rules are:
_specific properties_ > _generic properties_ > _specific configuration_ > _generic configuration_.

===== Probe configuration

You can configure the different aspect of the probes. These attributes can be configured for both the readiness and liveness probes or be specific to one.


.Probe configuration
|===
|Name |Description

|`type`
|The probe type among `http` (default), `tcp` and `exec`.

|`initial-delay`
|Number of seconds after the container has started before probes are initiated.

|`period`
|How often (in seconds) to perform the probe.

|`timeout`
|Number of seconds after which the probe times out.

|`success-threshold`
|Minimum consecutive successes for the probe to be considered successful after having failed.

|`failure-threshold`
|Minimum consecutive failures for the probe to be considered failed after having succeeded.

|===


More details about probes are available on https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/.

===== HTTP probe configuration

When using HTTP `GET` requests to determine readiness or liveness, several aspects can be configured. HTTP probes are used by default. To be more specific set the `type` attribute to `http`.

.HTTP probes configuration
|===
|Name |Description |Default

|`scheme`
|Scheme to use for connecting to the host.
|`HTTP`

|`path`
|Path to access on the HTTP server. An empty path disable the check
|

|`headers`
|Custom headers to set in the request. HTTP allows repeated headers. It cannot be configured using project's properties. An example is available below.
|

|`port`
|Number of the port to access on the container. A 0 or negative number disable the check.
|8080

|`port-name`
|Name of the port to access on the container. If neither the `port` or the `port-name` is set, the check is disabled. If both are set the configuration is considered invalid.
|

|===

Here is an example of HTTP probe configuration:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <initialDelay>3</initialDelay>
            <period>3</period>
            <liveness>
                <port>8081</port>
                <path>/ping</path>
                <scheme>HTTPS</scheme>
                <headers>
                    <X-Custom-Header>Awesome</X-Custom-Header>
                </headers>
            </liveness>
            <readiness>
                <!-- disable the readiness probe -->
                <port>-1</port>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

===== TCP probe configuration

You can also configure the probes to just open a socket on a specific port. The `type` attribute must be set to `tcp`.

.TCP probes configuration
|===
|Name |Description

|`port`
|Number of the port to access on the container. A 0 or negative number disable the check.

|`port-name`
|Name of the port to access on the container. If neither the `port` or the `port-name` is set, the check is disabled. If both are set the configuration is considered invalid.

|===

For example:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <initialDelay>3</initialDelay>
            <period>3</period>
            <liveness>
                <type>tcp</type>
                <port>8081</port>
            </liveness>
            <readiness>
                <-- use HTTP Get probe -->
                <path>/ping</path>
                <port>8080</port>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

===== Exec probe configuration

You can also configure the probes to execute a command. If the command succeeds, it returns 0, and Kubernetes consider the pod to be alive and healthy. If the command returns a non-zero value, Kubernetes kills the pod and restarts it. To use a command, you must set the `type` attribute to `exec`:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <config>
        <jkube-healthcheck-vertx>
            <initialDelay>3</initialDelay>
            <period>3</period>
            <liveness>
                <type>exec</type>
                <command>
                    <cmd>cat</cmd>
                    <cmd>/tmp/healthy</cmd>
                </command>
            </liveness>
            <readiness>
                <-- use HTTP Get probe -->
                <path>/ping</path>
                <port>8080</port>
            </readiness>
        </jkube-healthcheck-vertx>
    </config>
----

As you can see in the snippet above the command is passed using the `command` attribute. This attribute cannot be configured using project's properties. An empty command disables the check.

===== Disabling health checks

You can disables the checks by setting:

* the `port` to 0 or to a negative number for `http` and `tcp` probes
* the `command` to an empty list for `exec`

In the first case, you can use project's properties to disable them:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
    <!-- Disables `tcp` and `http` probes -->
    <vertx.health.port>-1</vertx.health.port>
----

For `http` probes, an empty or not set `path` also disable the probe.

[[jkube-maven-scm-enricher]]
==== jkube-maven-scm-enricher

This enricher adds additional https://maven.apache.org/pom.html#SCM[SCM] related metadata to all objects supporting annotations.
These metadata will be added only if https://maven.apache.org/pom.html#SCM[SCM] information is present in the maven `pom.xml` of the project.

The following annotations will be added to the objects that supports annotations,

.Maven SCM Enrichers Annotation Mapping
[cols="2,2,3"]
|===
| Maven SCM Info | Annotation | Description

| scm/connection
| jkube.io/scm-con-url
| The SCM connection that will be used to connect to the project's SCM

| scm/developerConnection
| jkube.io/scm-devcon-url
| The SCM Developer Connection that will be used to connect to the project's developer SCM

| scm/tag
| jkube.io/scm-tag
| The SCM tag that will be used to checkout the sources, like HEAD dev-branch etc.,

| scm/url
| jkube.io/scm-url
| The SCM web url that can be used to browse the SCM over web browser

|===

Lets say you have a maven pom.xml with the following scm information,
[source,xml]
----
<scm>
    <connection>scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git</connection>
    <developerConnection>scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git</developerConnection>
    <url>git://github.com/jkubeio/kubernetes-maven-plugin.git</url>
</scm>

----
This infomation will be enriched as annotations in the generated manifest like,

[source,yaml]
----
...
  kind: Service
  metadata:
    annotations
      jkube.io/scm-con-url: "scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git"
      jkube.io/scm-devcon-url: "scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git"
      jkube.io/scm-tag: "HEAD"
      jkube.io/scm-url: "git://github.com/jkubeio/kubernetes-maven-plugin.git"
...
----

[[jkube-maven-issue-mgmt-enricher]]
==== jkube-maven-issue-mgmt

This enricher adds additional https://maven.apache.org/pom.html#Issue_Management[Issue Management] related metadata to all objects supporting annotations.
These metadata will be added only if the https://maven.apache.org/pom.html#Issue_Management[Issue Management] information in available in maven `pom.xml` of the project.

The following annotations will be added to the objects that supports annotations,

.Maven Issue Tracker Enrichers Annotation Mapping
[cols="2,2,3"]
|===
| Maven Issue Tracker Info | Annotation | Description

| issueManagement/system
| jkube.io/issue-system
| The Issue Management system like Bugzilla, JIRA, GitHub etc.,

| issueManagement/url
| jkube.io/issue-tracker-url
| The Issue Management url e.g. GitHub Issues Url

|===

Lets say you have a maven pom.xml with the following issue management information,

[source,xml]
----
<issueManagement>
   <system>GitHub</system>
   <url>https://github.com/reactiverse/vertx-maven-plugin/issues/</url>
</issueManagement>
----

This information will be enriched as annotations in the generated manifest like,

[source,yaml]
----
...
  kind: Service
  metadata:
    annotations:
      jkube.io/issue-system: "GitHub"
      jkube.io/issue-tracker-url: "https://github.com/reactiverse/vertx-maven-plugin/issues/"
...
----

[[jkube-revision-history-enricher]]
==== jkube-revision-history

This enricher adds `spec.revisionHistoryLimit` property to deployment spec of Kubernetes/OpenShift resources.
A deployment’s revision history is stored in the replica sets, that specifies the number of old ReplicaSets to retain in order to allow rollback.
For more information read https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit[Kubernetes documentation].

The following configuration parameters can be used to influence the behaviour of this enricher:

.Default revision history enricher
[cols="2,2,3"]
|===
| Element | Description | Default

| limit
| Number of revision histories to retain
| 2
|===

Just as any other enricher you can specify required properties with in the enricher's configuration as below,

[source,xml]
----
...
<enricher>
    <config>
        <jkube-revision-history>
            <limit>8</limit>
        </jkube-revision-history>
    </config>
</enricher>
...
----

This information will be enriched as spec property in the generated manifest like,

[source,yaml]
----
...
kind: Deployment
spec:
  revisionHistoryLimit: 8
...
----

[[jkube-triggers-annotation]]
==== jkube-triggers-annotation

This enricher adds ImageStreamTag change triggers on Kubernetes resources that support the `image.openshift.io/triggers` annotation, such as StatefulSets, ReplicaSets and DaemonSets.

The trigger is added to all containers that apply, but can be restricted to a limited set of containers using the following configuration:

[source,xml]
----
...
<enricher>
    <config>
        <jkube-triggers-annotation>
            <containers>container-name-1,c2</containers>
        </jkube-triggers-annotation>
    </config>
</enricher>
...
----

[[jkube-configmap-file]]
==== jkube-configmap-file

This enricher adds ConfigMap defined as `resources` in plugin configuration and/or resolves file content from an annotation.

As XML you can define:

[source, xml]
.pom.xml
----
<configuration>
  <resources>
    <configMap>
      <name>myconfigmap</name>
      <entries>
        <entry>
          <name>A</name>
          <value>B</value>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
----

This creates a ConfigMap data with key `A` and value `B`.

You can also use `file` tag to refer to the content of a file.

[source, xml]
----
<configuration>
  <resources>
    <configMap>
      <name>configmap-test</name>
      <entries>
        <entry>
          <file>src/test/resources/test-application.properties</file>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
----

This creates a ConfigMap with key `test-application.properties` and value the content of the `src/test/resources/test-application.properties` file.
If you set `name` tag then this is used as key instead of the filename.

If you are defining a custom `ConfigMap` file, you can use an annotation to define a file name as key and its content as the value:

[source, yaml]
----
metadata:
  name: ${project.artifactId}
  annotations:
    maven.jkube.io/cm/application.properties: src/test/resources/test-application.properties
----

This creates a `ConfigMap` data with key `application.properties` (part defined after `cm`) and value the content of `src/test/resources/test-application.properties` file.

[[jkube-secret-file]]
==== jkube-secret-file

This enricher adds Secret defined as file content from an annotation.

If you are defining a custom `Secret` file, you can use an annotation to define a file name as key and its content as the value:

[source, yaml]
----
metadata:
  name: ${project.artifactId}
  annotations:
    maven.jkube.io/secret/application.properties: src/test/resources/test-application.properties
----

This creates a `Secret` data with the key `application.properties` (part defined after `secret`) and value content of `src/test/resources/test-application.properties` file (base64 encoded).

== Enricher API

_how to write your own enricher and install them_
