
[[extensions]]
= Extensions

This plugin provides two major extensions hook how the creation of images and resources descriptors can be customized:

* *Generators* are used to auto create or customize image configuration when creating Docker images. They are a bit like http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-generator-poms[Spring Boot Generator POMs] as they can be enabled or disabled by declaring a Maven dependency. Generators are able to examine the build and to _detect_ certain feature like whether Spring boot application is build or a plain war file. Depending on the collected information a base image or the exposed ports are selected automatically for creating a image build configuration.

* *Enrichers* are a similar concept but for creating the Kubernetes resource descriptors. Enricher can add build meta data as labels, automatically create `ReplicaSet` or `Service` based on the image performed. Again, enrichers can be selectively switched on and off via declaring Maven dependencies or via the XML configuration. kubernetes-maven-plugin already comes with a rich set of enrichers. Whereas *Generators* are only useful in the _Zero-Config_ case, *Enrichers* make sense for any configuration variant.

The following sections described which Generators and Enrichers are available and how own customizations can be hooked in.

include::extensions/_generator.adoc[]

include::extensions/_enricher.adoc[]
