
[[integrations]]
= Integrations

[[integrations.dekorate]]
== Dekorate

*{plugin}* provides a Zero Configuration approach to delegate deployment manifests
generation to https://github.com/dekorateio/dekorate[Dekorate].

Just by adding a dependency to Dekorate library in the `pom.xml` file, all manifest
generation will be delegated to Dekorate.

[source,xml,indent=2,subs="verbatim,quotes,attributes"]
----
<dependencies>
  <!-- ... -->
  <dependency>
      <groupId>io.dekorate</groupId>
      <artifactId>option-annotations</artifactId>
      <version>${dekorate.version}</version>
    </dependency>
    <dependency>
      <groupId>io.dekorate</groupId>
      <artifactId>openshift-annotations</artifactId>
      <version>${dekorate.version}</version>
    </dependency>
    <dependency>
      <groupId>io.dekorate</groupId>
      <artifactId>kubernetes-annotations</artifactId>
      <version>${dekorate.version}</version>
    </dependency>
    <dependency>
      <groupId>io.dekorate</groupId>
      <artifactId>dekorate-spring-boot</artifactId>
      <version>${dekorate.version}</version>
    </dependency>
</dependencies>
----

A full example of the integration can be found in the directory
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-dekorate[quickstarts/maven/spring-boot-dekorate].

An *experimental* feature is also provided to merge resources generated both by *{plugin}*
and Dekorate. You can activate this feature by using the following flag `-Djkube.mergeWithDekorate`
in the command-line, or setting it up as a property (`<jkube.mergeWithDekorate>true</jkube.mergeWithDekorate>`).

== JIB (Java Image Builder)
*{plugin}* also provides user an option to build container images without having access to any docker daemon. You just need to set `jkube.build.strategy` property to `jib`. It would delegate the build process to https://github.com/GoogleContainerTools/jib[JIB]. It creates a tarball inside your target directory which can be loaded into any docker daemon afterwards. You may also push the image to your specified registry using push goal with feature flag enabled.

You can find more details at https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-with-jib[Spring Boot JIB Quickstart]
