
[[introduction]]
= Introduction

The *{plugin}* brings your Java applications on to
ifeval::["{goal-prefix}" == "k8s"]
http://kubernetes.io/[Kubernetes].
endif::[]
ifeval::["{goal-prefix}" == "oc"]
https://www.openshift.com/[OpenShift].
endif::[]
It provides a tight integration into http://maven.apache.org[Maven] and benefits from the build configuration already provided.
This plugin focus on two tasks: _Building Docker images_ and _creating Kubernetes resource descriptors_.
It can be configured very flexibly and supports multiple configuration models for creating: A _Zero-Config_ setup allows for a quick ramp-up with some opinionated defaults.
For more advanced requirements, an _XML configuration_ provides additional configuration options which can be added to the `pom.xml`.
For the full power, in order to tune all facets of the creation, external _resource fragments_ and _Dockerfiles_ can be used.

[[building-images]]
== Building Images

The <<jkube:build>> goal is for creating Docker images containing the actual application. These then can be deployed later on Kubernetes or OpenShift.
It is easy to include build artifacts and their dependencies into these images.
This plugin uses the assembly descriptor format similar to the one used in
http://maven.apache.org/plugins/maven-assembly-plugin/[maven-assembly-plugin] to specify the content which will be added
to the image.
That images can then be pushed to public or private Docker registries with <<jkube:push>>.

Depending on the operational mode, for building the actual image either a Docker daemon is used directly or an https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#docker-build[OpenShift Docker Build] is performed.

A special <<jkube:watch>> goal allows for reacting to code changes to automatically recreate images or copy new artifacts into running containers.


[[resource-descriptors]]
== {cluster} Resources

{cluster} resource descriptors can be created or generated from <<jkube:resource>>.
These files are packaged within the Maven artifacts and can be deployed to a running orchestration platform with <<jkube:apply>>.

Typically you only specify a small part of the real resource descriptors which will be enriched by this plugin with various extra information taken from the `pom.xml`.
This drastically reduces boilerplate code for common scenarios.

== Configuration

As mentioned already there are three levels of configuration:

* *Zero-Config* mode makes some very opinionated decisions based on what is present in the pom.xml like what base image to use or which ports to expose.
This is great for starting up things and for keeping quickstart applications small and tidy.

* *XML plugin configuration* mode is similar to what https://dmp.fabric8.io/#example[docker-maven-plugin] provides.
This allows for type-safe configuration with IDE support, but only a subset of possible resource descriptor features is provided.

* *Kubernetes &amp; OpenShift resource fragments* are user provided YAML files that can be _enriched_ by the plugin. This allows expert users to use a plain configuration file with all their capabilities, but also to add project specific build information and avoid boilerplate code.

The following table gives an overview of the different models

.Configuration Models
[cols="1,4,3"]
|===
| Model | Docker Images | Resource Descriptors

| *Zero-Config*
| <<generators, Generators>> are used to create Docker image configurations. Generators can detect certain aspects of
  the build (e.g. whether Spring Boot is used) and then choose some opinionated defaults like the base image, which
  ports to expose and the startup command. They can be configured, but offer only a few options.
| Default <<enrichers, Enrichers>> will create a default _Service_ and _Deployment_ (_DeploymentConfig_ for OpenShift)
  when no other resource objects are provided. Depending on the image they can detect which port to expose in the
  service. As with Generators, Enrichers support a limited set of configuration options.

| *XML configuration*
| {plugin} inherits the XML based configuration for building images from the
  https://dmp.fabric8.io/#docker:build[docker-maven-plugin] and provides the same functionality. It supports an
  http://maven.apache.org/components/plugins/maven-assembly-plugin/assembly.html[assembly descriptor] for specifying the
  content of the Docker image.
| A subset of possible resource objects can be configured with a dedicated XML syntax. With a decent IDE you get
  autocompletion on most objects and inline documentation for the available configuration elements. The provided
  configuration can be still enhanced by Enhancers which is useful for adding e.g. labels and annotations containing
  build or other information.

| *Resource Fragments* and *Dockerfiles*
| Similarly to the docker-maven-plugin, {plugin} supports <<external-dockerfile,external Dockerfiles>> too, which are
  referenced from the plugin configuration.
| Resource descriptors can be provided as external YAML files which will build a base skeleton for the applicable resource.

  The "skeleton" is then post-processed by <<enrichers, Enrichers>> which will complete the skeleton by adding the fields
  each enricher is responsible of (labels, annotations, port information, etc.). Maven properties within these files
  are resolved to their values.

  With this model you can use every Kubernetes / OpenShift resource objects with all their flexibility, but still get the benefit
  of adding build information.
|===


== Examples

Let's have a look at some code. The following examples will demonstrate all three configurations variants:

[[zero-config]]
=== Zero-Config

This minimal but full working example `pom.xml` shows how a simple spring boot application can be dockerized and
prepared for Kubernetes. The full example can be found in directory
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/zero-config[quickstarts/maven/zero-config].

.Example
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.eclipse.jkube</groupId>
  <artifactId>jkube-maven-sample-zero-config</artifactId>
  <version>{version}</version>
  <packaging>jar</packaging>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId> <!--1-->
    <version>1.5.5.RELEASE</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId> <!--2-->
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId> <!--3-->
      </plugin>
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>{plugin}</artifactId> <!--4-->
        <version>{version}</version>
      </plugin>
    </plugins>
  </build>
</project>
----
<1> This minimalistic spring boot application uses the spring-boot parent POM for setting up dependencies and plugins
<2> The Spring Boot web starter dependency enables a simple embedded Tomcat for serving Spring MVC apps
<3> The `spring-boot-maven-plugin` is responsible for repackaging the application into a fat jar, including all dependencies and the embedded Tomcat
<4> The `{plugin}` enables the automatic generation of a Docker image and Kubernetes / OpenShift descriptors including this Spring application.

This setup make some opinionated decisions for you:

* As base image https://quay.io/repository/jkube/jkube-java-binary-s2i[jkube/jkube-java-binary-s2i]
  is chosen which enables https://www.jolokia.org[Jolokia] and https://github.com/prometheus/jmx_exporter[jmx_exporter].
  It also comes with a sophisticated https://github.com/jboss-openshift/cct_module/tree/master/jboss/container/java/run/bash[startup script].
* It will create a Kubernetes http://kubernetes.io/docs/user-guide/deployments/[Deployment] and a
  http://kubernetes.io/docs/user-guide/services/[Service] as resource objects
* It exports port 8080 as the application service port (and 8778 and 9779 for Jolokia and jmx_exporter access, respectively)

These choices can be influenced by configuration options as described in <<generator-spring-boot,Spring Boot Generator>>.

To start the Docker image build, you simply run

[source, bash, subs="+attributes"]
----
mvn package {goal-prefix}:build
----

This will create the Docker image against a running Docker daemon (which must be accessible either via Unix Socket or
with the URL set in `DOCKER_HOST`). Alternatively, when connected to an OpenShift cluster then a https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/index.html[S2I] build will be performed on OpenShift which at the end creates an
https://docs.openshift.com/enterprise/3.1/architecture/core_concepts/builds_and_image_streams.html[ImageStream].

To deploy the resources to the cluster call

[source, bash, subs="+attributes"]
----
mvn {goal-prefix}:resource {goal-prefix}:deploy
----

By default a _Service_ and a _Deployment_ object pointing to the created Docker image is created. When running in OpenShift mode, a _Service_ and _DeploymentConfig_ which refers the _ImageStream_ created with `{goal-prefix}:build` will be installed.

Of course you can bind all those jkube-goals to execution phases as well, so that they are called along with standard lifecycle goals like `install`. For example, to bind the building of the Kubernetes resource files and the Docker images, add the following goals to the execution of the {plugin}:

.Example for lifecycle bindings
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>{plugin}</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

If you'd also like to automatically deploy to Kubernetes each time you do a `mvn install` you can add the `apply` goal:

.Example for lifecycle bindings with automatic deploys for mvn install
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>{plugin}</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
        <goal>apply</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

=== XML Configuration

WARNING: XML based configuration is only partially implemented and is not recommended for use right now.

Although the Zero-config mode and its generators can be tweaked with options up to a certain degree, many cases require more flexibility. For such instances, an XML-based plugin configuration can be used, in a way similar to the
https://dmp.fabric8.io/#configuration[XML configuration] used by `docker-maven-plugin`.

The plugin configuration can be roughly divided into the following sections:

* Global configuration options are responsible for tuning the behaviour of plugin goals
* `<images>` defines which Docker <<image-configuration,images>> are used and configured. This section is similar to the
   https://dmp.fabric8.io//#image-configuration[image configuration] of the `docker-maven-plugin`, except that `<run>`
   and `<external>` sub-elements are ignored)
* `<resources>` defines the resource descriptors for deploying on an OpenShift or Kubernetes cluster.
* `<generator>` configures <<generators,generators>> which are responsible for creating images. Generators are used as an alternative to a dedicated `<images>` section.
* `<enricher>` configures various aspects of <<enrichers,enrichers>> for creating or enhancing resource descriptors.

A working example can be found in the
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/xml-config[quickstarts/maven/xml-config] directory.
An extract of the plugin configuration is shown below:

.Example for an XML configuration
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<configuration>
  <namespace>test-ns</namespace>
  <images>  <!--1-->
    <image>
      <name>xml-config-demo:1.0.0</name>
      <!-- "alias" is used to correlate to the containers in the pod spec -->
      <alias>camel-app</alias>
      <build>
        <from>fabric8/java-centos-openjdk8-jre</from>
        <assembly>
          <layers>
            <layer>
              <baseDirectory>/deployments</baseDirectory>
            </layer>
          </layers>
        </assembly>
        <env>
          <JAVA_LIB_DIR>/deployments</JAVA_LIB_DIR>
          <JAVA_MAIN_CLASS>org.apache.camel.cdi.Main</JAVA_MAIN_CLASS>
        </env>
      </build>
    </image>
  </images>

  <resources> <!--2-->
    <labels> <!--3-->
      <all>
        <group>quickstarts</group>
      </all>
    </labels>

    <controller>
      <replicas>2</replicas> <!--4-->
      <controllerName>${project.artifactId}</controllerName> <!--5-->
      <liveness> <!--6-->
        <getUrl>http://:8080/q/health</getUrl>
        <initialDelaySeconds>3</initialDelaySeconds>
        <timeoutSeconds>3</timeoutSeconds>
      </liveness>
      <startup> <!--7-->
        <failureThreshold>30</failureThreshold>
        <periodSeconds>10</periodSeconds>
        <getUrl>http://:8080/actuator/health</getUrl>
      </startup>
    </controller>

    <services> <!--8-->
      <service>
        <name>camel-service</name>
        <headless>true</headless>
      </service>
    </services>

    <serviceAccounts> <!--9-->
      <serviceAccount>
        <name>build-robot</name>
      </serviceAccount>
    </serviceAccounts>

    <annotations> <!--10-->
      <all>
        <version>${project.version}</version>
        <artifactId>${project.artifactId}</artifactId>
      </all>
      <deployment> <!--11-->
        <my>deployment</my>
      </deployment>
      <service>
        <property> <!--12-->
          <name>cloud.google.com/neg</name>
          <value>{"ingress":true}</value>
        </property>
      </service>
    </annotations>

    <configMap> <!--13-->
      <name>test</name>
      <entries>
        <entry> <!--14-->
          <name>key1</name>
          <value>value1</value>
        </entry>
        <entry> <!--15-->
          <name>key3</name>
          <file>${project.basedir}/src/main/resources/META-INF/resources/index.html</file>
        </entry>
      </entries>
    </configMap>

    <remotes> <!--16-->
       <remote>https://gist.githubusercontent.com/lordofthejars/ac2823cec7831697d09444bbaa76cd50/raw/e4b43f1b6494766dfc635b5959af7730c1a58a93/deployment.yaml</remote>
    </remotes>
  </resources>
</configuration>
----
<1> Standard XML configuration for building one single Docker image
<2> Kubernetes / OpenShift resources to create
<3> Labels which should be applied globally to all resource objects
<4> Number of replicas desired
<5> Name of controller created by plugin
<6> Liveness Probe to be added in PodTemplateSpec of Controller resource
<7> Startup Probe to be added in PodTemplateSpec of Controller resource
<8> One or more http://kubernetes.io/docs/user-guide/services/[Service] definitions.
<9> ServiceAccount(s) to create
<10> Annotations which should be applied either to all or to specific resources
<11> Annotations applied to Deployment resources only
<12> Annotations with a special character, a slash in this case 
<13> ConfigMap to be created
<14> ConfigMap data entry as a string key value pair
<15> ConfigMap data entry with value as file path, file's contents are loaded into ConfigMap as key value
<16> Remote files used as resource fragments.

The XML resource configuration is based on plain Kubernetes resource objects. When targeting OpenShift, Kubernetes resource descriptors will be automatically converted to their OpenShift counterparts, e.g. a Kubernetes http://kubernetes.io/docs/user-guide/deployments/[Deployment] will be converted to an OpenShift https://docs.openshift.com/container-platform/4.1/applications/deployments/what-deployments-are.html#deployments-and-deploymentconfigs_what-deployments-are[DeploymentConfig].

[[introduction-examples-resource-fragments]]
=== Resource Fragments

The third configuration option is to use an external configuration in form of YAML resource descriptors which are located in the  `src/main/jkube` directory. Each resource gets its own file, which contains a skeleton of a resource descriptor. The plugin will pick up the resource, enrich it and then combine all to a single `kubernetes.yml` and `openshift.yml` file. Within these descriptor files you are can freely use any Kubernetes feature.

Note: In order to support simultaneously both OpenShift and Kubernetes, there is currently no way to specify OpenShift-only features this way, though this might change in future releases.

Let's have a look at an example from
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/external-resources[quickstarts/maven/external-resources].
This is a plain Spring Boot application, whose images are auto generated like in the <<zero-config, Zero-Config>> case.
The resource fragments are in `src/main/jkube`.

.Example fragment "deployment.yml"
[source,yaml,indent=0,subs="verbatim,quotes,attributes"]
----
  spec:
    replicas: 1
    template:
      spec:
        volumes:
          - name: config
            gitRepo:
              repository: 'https://github.com/jstrachan/sample-springboot-config.git'
              revision: 667ee4db6bc842b127825351e5c9bae5a4fb2147
              directory: .
        containers:
          - volumeMounts:
              - name: config
                mountPath: /app/config
            env:
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        serviceAccount: ribbon
----

As you can see, there is no `metadata` section as would be expected for Kubernetes resources because it will be automatically added by the `{plugin}`. The object's `Kind`, if not given, is automatically derived from the
filename. In this case, the `{plugin}` will create a `Deployment` because the file is called `deployment.yml`. Similar mappings between file names and resource type exist for each supported resource kind, the
complete list of which (along with associated abbreviations) can be found in the <<default-kind-filename-mapping, Kind Filename Mapping>> section.



NOTE: Now that sidecar containers are supported in this plugin(if `jkube.sidecar` is enabled), be careful whenever you're supplying container name in the resource fragment. If container specified in resource fragment doesn't have a name or it's name is equal to default jkube generated application's container name; it would not be treated as sidecar and it would be merged into main container. However, You can override plugin's default name for main container via `jkube.generator.alias` property.

'''

Additionally, if you name your fragment using a name prefix followed by a dash and the mapped file name, the plugin will automatically use that name for your resource. So, for example, if you name your deployment fragment
`myapp-deployment.yml`, the plugin will name your resource `myapp`. In the absence of such provided name for your resource, a name will be automatically derived from your project's metadata (in particular, its `artifactId` as specified in your POM).

No image is also referenced in this example because the plugin also fills in the image details based on the configured image you are building with (either from a generator or from a dedicated image plugin configuration, as seen before).



NOTE: For building images there is also an alternative mode using external Dockerfiles, in addition to the XML based configuration. Refer to <<build-overview, {goal-prefix}:build>> for details.

'''

Enrichment of resource fragments can be fine-tuned by using profile sub-directories. For more details see <<profiles, Profiles>>.

Now that we have seen some examples of the various ways how this plugin can be used, the following sections will describe the plugin goals and extension points in detail.
