---
apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: revisionhistory
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: revisionhistory
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: revisionhistory
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          app.openshift.io/vcs-ref: "@ignore@"
          jkube.io/git-url: "@ignore@"
          app.openshift.io/vcs-uri: "@ignore@"
          jkube.io/git-commit: "@ignore@"
          jkube.io/git-branch: "@ignore@"
        labels:
          app: revisionhistory
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: repository/revisionhistory:latest
          imagePullPolicy: IfNotPresent
          name: repository-revisionhistory
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - repository-revisionhistory
        from:
          kind: ImageStreamTag
          name: revisionhistory:latest
      type: ImageChange
