The usual way to define Docker images is with the plugin configuration as explained in <<jkubeBuild>>. This can either be done completely within the `build.gradle` or by referring to an external Dockerfile.

However, this plugin provides an additional route for defining image configurations. This is done by so called _Generators_. A generator is a Java component providing an auto-detection mechanism for certain build types like a Spring Boot build or a plain Java build. As soon as a _Generator_ detects that it is applicable it will be called with the list of images configured in the `build.gradle`.

// TODO - Add when support is complete
//You can easily create your own generator as explained in <<generators-api, Generator API>>. This section will focus on existing generators and how you can configure them.

The included _Generators_ are enabled by default, but you can easily disable them or only select a certain set of generators. Each generator has a _name_, which is unique for a generator.

The generator configuration is embedded in a `generator` configuration section:

[[generator-example]]
.Example for a generator configuration
[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
{pluginExtension} {
  generator { //<1>
    includes = ['spring-boot'] //<2>
    config { //<3>
      'spring-boot' { //<4>
          alias = 'ping'
      }
    }
  }
}
----
<1> Start of generators' configuration.
<2> Generators can be included and excluded. Includes have precedence, and the generators are called in the given order.
<3> Configuration for individual generators.
<4> The config is a map of supported config values. Each section is embedded in a tag named after the generator.

The following sub-elements are supported:

.Generator configuration
[cols="1,6"]
|===
| Element | Description

| `includes`
| List of generator names which should be included. If given only this list of generators are included in this given order. The order is important because by default only the first matching generator kicks in. The generators from every active profile are included, too. However the generators listed here are moved to the front of the list, so that they are called first. Use the profile `raw` if you want to explicitly set the complete list of generators.

| `excludes`
| List of generator names to exclude. If set then all detected generators are used except the ones mentioned in this section.

| `config`
| Configuration for all generators. Each generator support a specific set of configuration values as described in the documentation. The subelements of this section are generator names to configure. E.g. for generator `spring-boot`, the sub-element is called `'spring-boot'`. This element then holds the specific generator configuration like `name` for specifying the final image name. See above for an example. Configuration coming from profiles are merged into this config, but not overriding the configuration specified here.
|===

Beside specifying generator configuration in the plugin's configuration it can be set directly with properties, too:

.Example generator property config
[source, sh, subs="+attributes"]
----
gradle k8sBuild -Pjkube.generator.java-exec.webPort=8082
----

The general scheme is a prefix `jkube.generator.` followed by the unique generator name and then the generator specific key.