---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9779"
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: micronaut-properties
        provider: jkube
        version: "0.1"
        group: org.eclipse.jkube.integration.tests.gradle.micronaut
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle.micronaut
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: micronaut-properties
        app.kubernetes.io/version: "0.1"
      name: micronaut-properties
    spec:
      ports:
        - name: glrpc
          port: 9080
          protocol: TCP
          targetPort: 9080
      selector:
        app: micronaut-properties
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle.micronaut
        app.kubernetes.io/name: micronaut-properties
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle.micronaut
        app.kubernetes.io/managed-by: jkube
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: micronaut-properties
        provider: jkube
        version: "0.1"
        group: org.eclipse.jkube.integration.tests.gradle.micronaut
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle.micronaut
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: micronaut-properties
        app.kubernetes.io/version: "0.1"
      name: micronaut-properties
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: micronaut-properties
          provider: jkube
          group: org.eclipse.jkube.integration.tests.gradle.micronaut
          app.kubernetes.io/name: micronaut-properties
          app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle.micronaut
          app.kubernetes.io/managed-by: jkube
      template:
        metadata:
          annotations:
            jkube.eclipse.org/git-commit: "@ignore@"
            jkube.eclipse.org/git-url: "@ignore@"
            jkube.eclipse.org/git-branch: "@ignore@"
          labels:
            app: micronaut-properties
            provider: jkube
            version: "0.1"
            group: org.eclipse.jkube.integration.tests.gradle.micronaut
            app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle.micronaut
            app.kubernetes.io/managed-by: jkube
            app.kubernetes.io/name: micronaut-properties
            app.kubernetes.io/version: "0.1"
          name: micronaut-properties
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: micronaut/micronaut-properties:0.1
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 9080
                  scheme: HTTP
                successThreshold: 1
              name: micronaut
              ports:
                - containerPort: 9080
                  name: glrpc
                  protocol: TCP
                - containerPort: 9779
                  name: prometheus
                  protocol: TCP
                - containerPort: 8778
                  name: jolokia
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 9080
                  scheme: HTTP
                successThreshold: 1
              securityContext:
                privileged: false
