[[resource-secrets]]
=== Secrets

ifeval::["{plugin-type}" == "maven"]
Once you've configured some docker registry credentials into `~/.m2/setting.xml`, as explained in the
<<authentication, Authentication>> section, you can create Kubernetes secrets from a server declaration.
endif::[]

**{plugin-configuration-type} configuration**

ifeval::["{plugin-type}" == "maven"]
You can create a secret using {plugin-configuration-type} configuration in the `pom.xml` file. It should contain the following fields:
endif::[]
ifeval::["{plugin-type}" == "gradle"]
You can create a secret using {plugin-configuration-type} configuration in the `build.gradle` file. It should contain the following fields:
endif::[]

[cols="1,1,6"]
|===
|key |required |description
ifeval::["{plugin-type}" == "maven"]
|**dockerServerId**
|`true`
|the server id which is configured in
`~/.m2/setting.xml`
endif::[]

|**name**
|`true`
|this will be used as name of the kubernetes secret resource

|**namespace**
|`false`
|the secret resource will be applied to the specific
namespace, if provided
|===

This is best explained by an example.

ifeval::["{plugin-type}" == "maven"]
include::maven/_secret_settings_configuration.adoc[]
endif::[]


**Yaml fragment with annotation**

You can create a secret using a yaml fragment. You can reference the docker server id with an annotation
`jkube.eclipse.org/dockerServerId`. The yaml fragment file should be put under
the `src/main/jkube/` folder.

.Example

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mydockerkey
  namespace: default
  annotations:
    jkube.eclipse.org/dockerServerId: ${docker.registry}
type: kubernetes.io/dockercfg
----