[[serviceaccount-generation]]
=== ServiceAccount Generation

You can configure `resources` configuration to generate a ServiceAccount or configure an already existing ServiceAccount into your generated Deployment.

Here is an example of {plugin-configuration-type} configuration to generate a ServiceAccount:

ifeval::["{plugin-type}" == "maven"]
include::maven/_serviceaccounts_configuration.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_serviceaccounts_configuration.adoc[]
endif::[]


If you don't want to generate ServiceAccount but just use an existing ServiceAccount in your Deployment. You can configure it via `serviceAccount` field in resource configuration. Here is an example:

ifeval::["{plugin-type}" == "maven"]
include::maven/_serviceaccount_configuration.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_serviceaccount_configuration.adoc[]
endif::[]

**Service Account Resource fragment**:

If you don't want to use {plugin-configuration-type} configuration, you can provide a resource fragment for ServiceAccount resource. Here is how it would look like:

.ServiceAccount resource fragment
[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
----