FROM image AS stage1
MAINTAINER maintainer@example.com
EXPOSE 8080/udp
COPY /src /export/dest
WORKDIR /tmp
RUN echo something
RUN echo second
VOLUME ["/vol1"]
CMD ["c1","c2"]

FROM image2
MAINTAINER maintainer@example.com
EXPOSE 8080/udp
COPY --from=stage1 /src /export/dest
WORKDIR /tmp
RUN echo something
RUN echo second
VOLUME ["/vol1"]
CMD ["c1","c2"]
