---
apiVersion: v1
kind: List
items:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      labels:
        app: controller
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: controller
    spec:
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: controller
                provider: jkube
                version: "@ignore@"
                group: org.eclipse.jkube.integration.tests.gradle
            spec:
              containers:
                - name: repository-controller
                  image: repository/controller:latest
                  imagePullPolicy: IfNotPresent
                  securityContext:
                    privileged: false
                  env:
                    - name: KUBERNETES_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
              restartPolicy: OnFailure
      schedule: '*/2 * * * *'
