
[[profiles]]
= Profiles

Profiles can be used to combine a set of enrichers and generators and to give this combination a referable name.

Profiles are defined in YAML. The following example shows a simple profile which uses only the
<<generator-spring-boot, Spring Boot generator>> and a few enrichers to add a Kubernetes
Deployment and a Service:

.Profile Definition
[source, yaml]
----
- name: my-spring-boot-apps # <1>
  generator: # <2>
    includes:
      - spring-boot
  enricher: # <3>
    includes: # <4>
      # Default Deployment object
      - jkube-controller
      # Add a default service
      - jkube-service
    excludes: # <5>
      - jkube-icon
    config: # <6>
      jkube-service:
        # Expose service as NodePort
        type: NodePort
  order: 10 # <7>
- name: another-profile
# ....
----
<1> Profile's name
<2> <<generators, Generators>> to use
<3> <<enrichers, Enrichers>> to use
<4> List of enrichers to *include* in that given order
<5> List of enrichers to *exclude* (especially useful when extending profiles)
<6> Configuration for services an enrichers
<7> An order which influences the way how profiles with the same name are merged

Each `profiles.yml` has a list of profiles which are defined with these elements:

.Profile elements
[cols="1,6"]
|===
| Element | Description

| *name*
| Profile name.

| *extends*
| This plugin comes with a set of <<profiles-predefined, predefined profiles>>.
  These profiles can be extended by defining a custom profile that references the name of the
  profile to extend in the `extends` field.

| *generator*
| List of generator definitions. See <<generator-enricher-definition, below>> for the format of these definitions.

| *enricher*
| List of enrichers definitions. See <<generator-enricher-definition, below>> for the format of these definitions.

| *order*
| The order of the profile which is used when profiles of the same name are merged.
|===

[[generator-enricher-definition]]
== Generator and Enricher definitions

The definition of generators and enrichers in the profile follows the same format:

.Generator and Enricher definition
[cols="1,6"]
|===
| Element | Description

| *includes*
| List of generators or enrichers to include. The order in the list determines the order in which the processors are applied.

| *excludes*
| List of generators or enrichers. These have precedences over _includes_ and will exclude a processor even when referenced in an _includes_ sections

| *config*
| Configuration for generators or enrichers. This is a map where the keys are the name of the processor to configure and the value is again a map with configuration keys and values specific to the processor. See the documentation of the respective generator or enricher for the available configuration keys.
|===

[[profiles-lookup-order]]
== Lookup order

Profiles can be defined externally either directly as a build resource in `src/main/jkube/profiles.yml` or provided as part of a plugin's dependency where it is supposed to be included as `META-INF/jkube/profiles.yml`. Multiple profiles can be included in these `profiles.yml` descriptors as a list:

If a profile is <<profiles-using, used>> then it is looked up from various places in the following order:

* From the compile and plugin classpath from `META-INF/jkube/profiles-default.yml`. These files are reserved for profiles defined by this plugin
* From the compile and plugin classpath from `META-INF/jkube/profiles.yml`. Use this location for defining your custom profiles which you want to include via dependencies.
* From the project in `src/main/jkube/profiles.yml`. The directory can be tuned with the plugin option `resourceDir` (property: `jkube.resourceDir`)

When multiple profiles of the same name are found, then these profiles are merged.
If the profiles have an order number, then the profile with _higher_ order takes precedence
when merging.

For _includes_ of the same processors, the processor is moved to the earliest position.
e.g. consider the following two profiles with the name `my-profile`

.Profile A
[source, yaml]
----
name: my-profile
enricher:
  includes: [ e1, e2 ]
----

.Profile B
[source, yaml]
----
name: my-profile
enricher:
  includes: [ e3, e1 ]
order: 10
----

then when merged results in the following profile (when no order is given, it defaults to 0):

.Profile merged
[source, yaml]
----
name: my-profile
enricher:
  includes: [ e1, e2, e3 ]
order: 10
----

Profile with the same order number are merged according to the lookup order described above, where the latter profile is supposed to have a higher order.

The configuration for enrichers and generators are merged, too, where higher order profiles override configuration values with the same key of lower order profile configuration.

[[profiles-using]]
== Using Profiles

Profiles can be selected by defining them in the plugin configuration, by giving a system property or by using
<<profiles-resource-fragments,special directories>> in the directory holding the resource fragments.

.Profile used in plugin configuration

Here is an example how the profile can be used in a plugin configuration:

include::{plugin-type}/_example_plugin_configuration.adoc[]

.Profile as property

Alternatively a profile can be also specified on the command line or as a project property:

include::{plugin-type}/_example_property_configuration.adoc[]

If a configuration for enrichers and generators is provided as part of the project plugin's configuration then this takes precedence and overrides any of the defaults provided by the selected profile.

[[profiles-resource-fragments]]
.Profiles for resource fragments

Profiles are also very useful when used together with resource fragments in `src/main/jkube`.
By default, the resource objects defined here are enriched with the configured profile (if any).
A different profile can be selected easily by using a subdirectory within `src/main/jkube`.
The name of each subdirectory is interpreted as a profile name and all resource definition files found in this subdirectory are enhanced with the enhancers defined in this profile.

For example, consider the following directory layout:

[source, subs="+attributes"]
----
.
├── src/main/jkube
  ├── app-rc.yml
  ├── app-svc.yml
  └── raw
    ├── couchbase-rc.yml
    └── couchbase-svc.yml
----

Here, the resource descriptors `app-rc.yml` and `app-svc.yml` are enhanced with the enrichers defined in the main configuration.
The two  files `couchbase-rc.yml` and `couchbase-svc.yml` in the subdirectory `raw/` are enriched with the profile **raw** instead.
This is a predefined profile which includes no enricher at all, so the couchbase resource objects are not enriched and taken over literally.
This is an easy way how you can fine tune enrichment for different object set.

[[profiles-predefined]]
== Predefined Profiles

This plugin comes with the following predefined profiles:

.Predefined Profiles
[cols="1,6"]
|===
| Profile | Description

| *default*
| The default profile which is active if no profile is specified. It consists of a curated set of generator and enrichers. See <<profiles-default,below>> for the current definition.

| *minimal*
| This profile contains no generators and only enrichers for adding default objects (controller and services). No other enrichment is included.

| *explicit*
| Like default but without adding default objects like controllers and services.

| *aggregate*
| Includes no generators and only the <<jkube-dependency,jkube-dependency>> enricher for picking up and combining resources from the compile time dependencies.

| *internal-microservice*
| _default_ profile extension that prevents services from being externally exposed.

| *security-hardening*
| _default_ profile extension that enables the <<jkube-security-hardening,security-hardening>>
  enricher.
|===

[[profiles-extended]]
== Extending Profiles

A profile can also extend another profile to avoid repetition.
This is useful to add optional enrichers/generators to a given profile or to partially exclude enrichers/generators from another.

[source, yaml]
----
- name: security-hardening
  extends: default
  enricher:
    includes:
      - jkube-security-hardening
----
For example, this profiles includes the optional `jkube-security-hardening` enricher to the default profile.
