#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Bug report 🐞
description: Report a bug found in Eclipse JKube
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ### Creating a new Bug 🐞
        🔍  Before opening a new issue please search existing issues at https://github.com/eclipse/jkube/issues

        🤔  To make it easier for us to help you, please include as much useful information as possible.

        Useful Links:

          - 📄  Documentation: https://www.eclipse.dev/jkube/docs/
          - 📝  Contributing: https://www.eclipse.dev/jkube/contributing/


  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Eclipse JKube version
      description: Eclipse JKube version (can be found in pom.xml dependency or build.gradle implementation section)
      options:
        - "SNAPSHOT"
        - "1.16.2"
        - "1.15.0"
        - "1.14.0"
        - "1.13.1"
        - "1.12.0"
        - "1.11.0"
        - "1.10.1"
        - "1.9.1"
        - "1.8.0"
        - "1.7.0"
        - "1.6.0"
        - "1.5.1"
        - "1.4.0"
        - "1.3.0"
        - "1.2.0"
        - "1.1.1"
        - "1.0.2"
        - "other (please specify in additional context)"
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Component
      options:
        - "Kubernetes Maven Plugin"
        - "Kubernetes Gradle Plugin"
        - "OpenShift Maven Plugin"
        - "OpenShift Gradle Plugin"
        - "JKube Kit"
    validations:
      required: true
  - type: dropdown
    id: maven-version
    attributes:
      label: Apache Maven version
      description: Apache Maven version
      options:
        - "3.8.5"
        - "3.8.4"
        - "3.8.3"
        - "3.8.1"
        - "3.6.3"
        - "3.6.2"
        - "3.6.1"
        - "3.6.0"
        - "3.5.4"
        - "3.5.3"
        - "3.5.2"
        - "3.5.0"
        - "other (please specify in additional context)"
    validations:
      required: false
  - type: dropdown
    id: gradle-version
    attributes:
      label: Gradle version
      description: Gradle version
      options:
        - "7.4.2"
        - "7.4.1"
        - "7.4"
        - "7.3.3"
        - "7.3.2"
        - "7.3.1"
        - "7.3"
        - "7.2"
        - "7.1.1"
        - "7.1"
        - "7.0.1"
        - "7.0"
        - "other (please specify in additional context)"
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What are the steps to reproduce this bug ?
      placeholder: |
        1. Configure '...'
        2. Run '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder:
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      description: What is the kubernetes flavor ?
      multiple: true
      options:
        - Kubernetes (vanilla)
        - OpenShift
        - minikube
        - CodeReady Container
        - other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: api-version
    attributes:
      label: Kubernetes API Server version
      description: Kubernetes API Server version
      options:
        - "1.25.3"
        - "next (development version)"
        - "1.24.7"
        - "1.23.13"
        - "1.22.15"
        - "other (please specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Amazon
        - Azure
        - GKE
        - "Dev Sandbox (workspaces.openshift.com)"
        - other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Eclipse JKube Logs
      placeholder: |
        Please copy and paste any relevant log output.

        This will be automatically formatted into code, so no need for backticks
      description:
      render: shell

  - type: textarea
    id: sample-reproducer-project
    attributes:
      label: Sample Reproducer Project
      placeholder: |
        Sample Reproducer project which can reproduce abovementioned issue

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder:
