
[[introduction]]
= Introduction

The *openshift-maven-plugin* (oc-m-p) brings your Java applications on to https://www.openshift.com/[Openshift].
It provides a tight integration into http://maven.apache.org[Maven] and benefits from the build configuration already provided.
This plugin focus on two tasks: _Building Docker images_ and _creating Kubernetes resource descriptors_.
It can be configured very flexibly and supports multiple configuration models for creating: A _Zero-Config_ setup allows for a quick ramp-up with some opinionated defaults.
For more advanced requirements, an _XML configuration_ provides additional configuration options which can be added to the `pom.xml`.
For the full power, in order to tune all facets of the creation, external _resource fragments_ and _Dockerfiles_ can be used.

[[building-images]]
== Building Images

The <<oc:build>> goal is for creating Docker images containing the actual application. These then can be deployed later on Kubernetes or OpenShift.
It is easy to include build artifacts and their dependencies into these images.
This plugin uses the assembly descriptor format from the http://maven.apache.org/plugins/maven-assembly-plugin/[maven-assembly-plugin] to specify the content which will be added to the image.
That images can then be pushed to public or private Docker registries with <<oc:push>>.

Depending on the operational mode, for building the actual image either a Docker daemon is used directly or an https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#docker-build[OpenShift Docker Build] is performed.

A special <<oc:watch>> goal allows for reacting to code changes to automatically recreate images or copy new artifacts into running containers.

These image related features are inherited from the https://github.com/jkubeio/docker-maven-plugin[jkubeio/docker-maven-plugin] which is part of this plugin.

[[resource-descriptors]]
== Openshift Resources

Openshift resource descriptors can be created or generated from <<oc:resource>>.
These files are packaged within the Maven artifacts and can be deployed to a running orchestration platform with <<oc:apply>>.

Typically you only specify a small part of the real resource descriptors which will be enriched by this plugin with various extra information taken from the `pom.xml`.
This drastically reduces boilerplate code for common scenarios.

== Configuration

As mentioned already there are three levels of configuration:

* *Zero-Config* mode makes some very opinionated decisions based on what is present in the pom.xml like what base image to use or which ports to expose.
This is great for starting up things and for keeping quickstart applications small and tidy.

* *XML plugin configuration* mode is similar to what https://jkubeio.github.io/docker-maven-plugin/#example[docker-maven-plugin] provides.
This allows for type-safe configuration with IDE support, but only a subset of possible resource descriptor features is provided.

* *Kubernetes &amp; OpenShift resource fragments* are user provided YAML files that can be _enriched_ by the plugin. This allows expert users to use a plain configuration file with all their capabilities, but also to add project specific build information and avoid boilerplate code.

The following table gives an overview of the different models

.Configuration Models
[cols="1,4,3"]
|===
| Model | Docker Images | Resource Descriptors

| *Zero-Config*
| <<generators, Generators>> are used to create Docker image configurations. Generators can detect certain aspects of the build (e.g. whether Spring Boot is used) and then choose some default like the base image, which ports to expose and the startup command. They can be configured, but offer only a few options.
| Default <<enrichers, Enrichers>> will create a default _Service_ and _Deployment_ (_DeploymentConfig_ for OpenShift) when no other resource objects are provided. Depending on the image they can detect which port to expose in the service. As with Generators, Enrichers support a limited set of configuration options.

| *XML configuration*
| oc-m-p inherits the XML based configuration for building images from the https://jkubeio.github.io/docker-maven-plugin/#docker:build[docker-maven-plugin] and provides the same functionality. It supports an http://maven.apache.org/components/plugins/maven-assembly-plugin/assembly.html[assembly descriptor] for specifying the content of the Docker image.
| A subset of possible resource objects can be configured with a dedicated XML syntax. With a decent IDE you get autocompletion on most object and inline documentation for the available configuration elements. The provided configuration can be still enhanced by Enhancers which is useful for adding e.g. labels and annotations containing build or other information.

| *Resource Fragments* and *Dockerfiles*
| Similarly to the docker-maven-plugin, oc-m-p supports <<external-dockerfile,external Dockerfiles>> too, which are referenced from the plugin configuration.
| Resource descriptors can be provided as external YAML files which specify a skeleton. This skeleton is then filled by Enrichers which add labels and more. Maven properties within these files are resolved to thier values. With this model you can use every Kubernetes / OpenShift resource object with all their flexibility, but still get the benefit of adding build information.
|===


== Examples

Let's have a look at some code. The following examples will demonstrate all three configurations variants:

[[zero-config]]
=== Zero-Config

This minimal but full working example `pom.xml` shows how a simple spring boot application can be dockerized and prepared for Kubernetes. The full example can be found in directory https://github.com/jkubeio/kubernetes-maven-plugin/tree/master/samples/zero-config[samples/zero-config].

.Example
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.jkube</groupId>
  <artifactId>jkube-maven-sample-zero-config</artifactId>
  <version>{version}</version>
  <packaging>jar</packaging>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId> <!--1-->
    <version>1.5.5.RELEASE</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId> <!--2-->
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId> <!--3-->
      </plugin>
      <plugin>
        <groupId>io.jkube</groupId>
        <artifactId>oc-maven-plugin</artifactId> <!--4-->
        <version>{version}</version>
      </plugin>
    </plugins>
  </build>
</project>
----
<1> This minimalistic spring boot application uses the spring-boot parent POM for setting up dependencies and plugins
<2> The Spring Boot web starter dependency enables a simple embedded Tomcat for serving Spring MVC apps
<3> The `spring-boot-maven-plugin` is responsible for repackaging the application into a fat jar, including all dependencies and the embedded Tomcat
<4> The `kubernetes-maven-plugin` enables the automatic generation of a Docker image and Kubernetes / OpenShift descriptors including this Spring application.

This setup make some opinionated decisions for you:

* As base image https://github.com/fabric8io-images/java/tree/master/images/jboss/openjdk8/jdk[jkube/java-jboss-openjdk8-jdk] is chosen which enables https://www.jolokia.org[Jolokia] and https://github.com/prometheus/jmx_exporter[jmx_exporter]. It also comes with a sophisticated https://github.com/jkubeio-images/run-java-sh[startup script].
* It will create a Kubernetes http://kubernetes.io/docs/user-guide/deployments/[Deployment] and a http://kubernetes.io/docs/user-guide/services/[Service] as resource objects
* It exports port 8080 as the application service port (and 8778 and 9779 for Jolokia and jmx_exporter access, respectively)

These choices can be influenced by configuration options as decribed in <<generator-spring-boot,Spring Boot Generator>>.

To start the Docker image build, you simply run

[source,bash]
----
mvn package oc:build
----

This will create the Docker image against a running Docker daemon (which must be accessible either via Unix Socket or with the URL set in `DOCKER_HOST`). Alternatively, when connected to an OpenShift cluster (or using the `openshift` <<build-mode,mode>> explicitly), then a Docker build will be performed on OpenShift which at the end creates an https://docs.openshift.com/enterprise/3.1/architecture/core_concepts/builds_and_image_streams.html[ImageStream].

To deploy the resources to the cluster call

[source,bash]
----
mvn oc:resource oc:deploy
----

By default a _Service_ and a _Deployment_ object pointing to the created Docker image is created. When running in OpenShift mode, a _Service_ and _DeploymentConfig_ which refers the _ImageStream_ created with `oc:build` will be installed.

Of course you can bind all those jkube.goals to execution phases as well, so that they are called along with standard lifecycle goals like `install`. For example, to bind the building of the Kubernetes resource files and the Docker images, add the following goals to the execution of the f-m-p:

.Example for lifecycle bindings
[source, xml, indent=0]
----
<plugin>
  <groupId>io.jkube</groupId>
  <artifactId>oc-maven-plugin</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

If you'd also like to automatically deploy to Kubernetes each time you do a `mvn install` you can add the `deploy` goal:

.Example for lifecycle bindings with automatic deploys for mvn install
[source, xml, indent=0]
----
<plugin>
  <groupId>io.jkube</groupId>
  <artifactId>oc-maven-plugin</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
        <goal>deploy</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

=== XML Configuration

WARNING: XML based configuration is only partially implemented and is not recommended for use right now.

Although the Zero-config mode and its generators can be tweaked with options up to a certain degree, many cases require more flexibility. For such instances, an XML-based plugin configuration can be used, in a way similar to the
https://jkubeio.github.io/docker-maven-plugin/#configuration[XML configuration] used by `docker-maven-plugin`.

The plugin configuration can be roughly divided into the following sections:

* Global configuration options are responsible for tuning the behaviour of plugin goals
* `<images>` defines which Docker <<image-configuration,images>> are used and configured. This section is similar to the https://jkubeio.github.io/docker-maven-plugin/#image-configuration[image configuration] of the `docker-maven-plugin`, except that `<run>` and `<external>` sub-elements are ignored)
* `<resource>` defines the resource descriptors for deploying on an OpenShift or Kuberneres cluster.
* `<generator>` configures <<generators,generators>> which are responsible for creating images. Generators are used as an alternative to a dedicated `<images>` section.
* `<enricher>` configures various aspects of <<enrichers,enrichers>> for creating or enhancing resource descriptors.

A working example can be found in the  https://github.com/jkubeio/kubernetes-maven-plugin/tree/master/samples/xml-config[samples/xml-config] directory. An extract of the plugin configuration is shown below:

.Example for an XML configuration
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<configuration>
  <namespace>test-ns</namespace>
  <images>  <!--1-->
    <image>
      <name>xml-config-demo:1.0.0</name>
      <!-- "alias" is used to correlate to the containers in the pod spec -->
      <alias>camel-app</alias>
      <build>
        <from>jkube.java</from>
        <assembly>
          <basedir>/deployments</basedir>
          <descriptorRef>artifact-with-dependencies</descriptorRef>
        </assembly>
        <env>
          <JAVA_LIB_DIR>/deployments</JAVA_LIB_DIR>
          <JAVA_MAIN_CLASS>org.apache.camel.cdi.Main</JAVA_MAIN_CLASS>
        </env>
      </build>
    </image>
  </images>

  <resources> <!--2-->
    <labels> <!--3-->
      <all>
        <group>quickstarts</group>
      </all>
    </labels>

    <deployment> <!--4-->
      <name>${project.artifactId}</name>
      <replicas>1</replicas>

      <containers> <!--5-->
        <container>
          <alias>camel-app</alias> <!--6-->
          <ports>
            <port>8778</port>
          </ports>
          <mounts>
            <scratch>/var/scratch</scratch>
          </mounts>
        </container>
      </containers>

      <volumes> <!--7-->
        <volume>
          <name>scratch</name>
          <type>emptyDir</type>
        </volume>
      </volumes>
    </deployment>

    <services> <!--8-->
      <service>
        <name>camel-service</name>
        <headless>true</headless>
      </service>
    </services>

    <serviceAccounts>
      <serviceAccount>
        <name>build-robot</name>
      </serviceAccount>
    </serviceAccounts>
  </resources>
</configuration>
----
<1> Standard docker-maven-plugin configuration for building one single Docker image
<2> Kubernetes / OpenShift resources to create
<3> Labels which should be applied globally to all resource objects
<4> Definition of a http://kubernetes.io/docs/user-guide/deployments/[Deployment] to create
<5> Containers to include in the deployment
<6> An _alias_ is used to correlate a container's image with the image definition in the `<images>` section where each image carry an alias. Can be omitted if only a single image is used
<7> http://kubernetes.io/docs/user-guide/volumes/[Volume] definitions used in a Deployment's _ReplicaSet_
<8> One or more http://kubernetes.io/docs/user-guide/services/[Service] definitions.

The XML resource configuration is based on plain Kubernetes resource objects. When targeting OpenShift, Kubernetes resource descriptors will be automatically converted to their OpenShift counterparts, e.g. a Kubernetes http://kubernetes.io/docs/user-guide/deployments/[Deployment] will be converted to an OpenShift https://docs.openshift.org/latest/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations[DeploymentConfig].

=== Resource Fragments

The third configuration option is to use an external configuration in form of YAML resource descriptors which are located in the  `src/main/jkube` directory. Each resource get its own file, which contains a skeleton of a resource descriptor. The plugin will pick up the resource, enrich it and then combine all to a single `kubernetes.yml` and `openshift.yml` file. Within these descriptor files you are can freely use any Kubernetes feature.

Note: In order to support simultaneously both OpenShift and Kubernetes, there is currently no way to specify OpenShift-only features this way, though this might change in future releases.

Let's have a look at an example from https://github.com/rhuss/kubernetes-maven-plugin/tree/master/samples/external-resources[samples/external-resources]. This is a plain Spring Boot application, whose images are auto generated like in the <<zero-config, Zero-Config>> case. The resource fragments are in `src/main/jkube`.

.Example fragment "deployment.yml"
[source,yaml,indent=0,subs="verbatim,quotes,attributes"]
----
  spec:
    replicas: 1
    template:
      spec:
        volumes:
          - name: config
            gitRepo:
              repository: 'https://github.com/jstrachan/sample-springboot-config.git'
              revision: 667ee4db6bc842b127825351e5c9bae5a4fb2147
              directory: .
        containers:
          - volumeMounts:
              - name: config
                mountPath: /app/config
            env:
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        serviceAccount: ribbon
----

As you can see, there is no `metadata` section as would be expected for Kubernetes resources because it will be automatically added by the `kubernetes-maven-plugin`. The object's `Kind`, if not given, is automatically derived from the
filename. In this case, the `kubernetes-maven-plugin` will create a `Deployment` because the file is called `deployment.yml`. Similar mappings between file names and resource type exist for each supported resource kind, the
complete list of which (along with associated abbreviations) can be found in the <<appendix-kind-mapping, Appendix>>.



NOTE: Now that sidecar containers are supported in this plugin, be careful whenever you're supplying container name in the resource fragment. If container specified in resource fragment doesn't have a name or it's name is equal to default fmp generated application's container name; it would not be treated as sidecar and it would be merged into main container. However, You can override plugin's default name for main container via `jkube.generator.alias` property.

'''

Additionally, if you name your fragment using a name prefix followed by a dash and the mapped file name, the plugin will automatically use that name for your resource. So, for example, if you name your deployment fragment
`myapp-deployment.yml`, the plugin will name your resource `myapp`. In the absence of such provided name for your resource, a name will be automatically derived from your project's metadata (in particular, its `artifactId` as specified in your POM).

No image is also referenced in this example because the plugin also fills in the image details based on the configured image you are building with (either from a generator or from a dedicated image plugin configuration, as seen before).



NOTE: For building images there is also an alternative mode using external Dockerfiles, in addition to the XML based configuration. Refer to <<build-overview, oc:build>> for details.

'''

Enrichment of resource fragments can be fine-tuned by using profile sub-directories. For more details see <<profiles, Profiles>>.

Now that we have seen some examples for the various ways how this plugin can be used, the following sections will describe the plugin goals and extension points in detail.
