---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    jkube.helm.sh/provided-value: "${golang_expression}"
    jkube.helm.sh/provided-value-scalar: "${golang_expression_scalar}"
  labels:
    app: helm-and-fragments
    provider: jkube
    version: "@ignore@"
    group: org.eclipse.jkube
  name: helm-and-fragments
