#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      provider: jkube
      app: deployment-strategy-type-919
      version: 0.1-SNAPSHOT
      group: org.eclipse.jkube.devops.apps
    name: jkube-docker-registry
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        provider: jkube
        app: deployment-strategy-type-919
        group: org.eclipse.jkube.devops.apps
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          provider: jkube
          app: deployment-strategy-type-919
          version: 0.1-SNAPSHOT
          group: org.eclipse.jkube.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: registry:2
          imagePullPolicy: IfNotPresent
          name: jkube-docker-registry
          ports:
          - containerPort: 5000
            name: http
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: /var/lib/registry
            name: jkube-docker-registry-storage
            readOnly: false
        initContainers:
        - command:
          - chmod
          - "777"
          - /var/lib/registry
          image: busybox
          imagePullPolicy: IfNotPresent
          name: jkube-volume-permission
          volumeMounts:
          - mountPath: /var/lib/registry
            name: jkube-docker-registry-storage
        volumes:
        - name: jkube-docker-registry-storage
          persistentVolumeClaim:
            claimName: jkube-docker-registry-storage
