[[authentication]]
= Registry Authentication

When pulling (via the `autoPull` mode of `{task-prefix}Build`) or pushing image, it
might be necessary to authenticate against a Docker registry.

There are five different locations searched for credentials.  In order, these are:

* Providing system properties `jkube.docker.username` and `jkube.docker.password` from the outside.
* Using a `authConfig` section in the plugin configuration with `username` and `password` elements.
* Using OpenShift configuration in `~/.config/kube`
* Login into a registry with `docker login` (credentials in a credential helper or in `~/.docker/config.json`)

Using the username and password directly in the `build.gradle` is not
recommended since this is widely visible. This is the easiest and
transparent way, though. Using an `authConfig` is straight forward:

[source,groovy,subs="attributes+"]
----
{pluginExtension} {
    images {
        image {
            name = "consol/tomcat-7.0"
        }
    }
    authConfig {
        username = "jolokia"
        password = "s!cr!t"
    }
}
----

The system property provided credentials are a good compromise when
using CI servers like Jenkins. You simply provide the credentials from
the outside:

.Example
[source, sh, subs="+attributes"]
----
gradle -Djkube.docker.username=jolokia -Djkube.docker.password=s!cr!t {task-prefix}Push
----

The most _secure_ way is to rely on docker's credential store or credential helper and read confidential information
from an external credentials store, such as the native keychain of the operating system. Follow the instruction on
https://docs.docker.com/engine/reference/commandline/login/#credentials-store[the docker login documentation].

As a final fallback, this plugin consults `$DOCKER_CONFIG/config.json` if `DOCKER_CONFIG` is set, or `~/.docker/config.json` if not, and reads credentials stored directly within this
file. This unsafe behavior happened when connecting to a registry with the command `docker login` from the command line
with older versions of docker (pre 1.13.0) or when docker is not configured to use a
https://docs.docker.com/engine/reference/commandline/login/#credentials-store[credential store].

== Pull vs. Push Authentication

The credentials lookup described above is valid for both push and
pull operations. In order to narrow things down, credentials can be
provided for pull or push operations alone:

In an `authConfig` section a sub-section `pull` and/or `push`
can be added. In the example below the credentials provider are only
used for image push operations:

.Example
[source,groovy,subs="attributes+"]
----
{pluginExtension} {
    images {
        image {
            name = "consol/tomcat-7.0"
        }
    }
    authConfig {
        push {
            username = "jolokia"
            password = "secret"
        }
    }
}
----

When the credentials are given on the command line as system
properties, then the properties `jkube.docker.pull.username` /
`jkube.docker.pull.password` and `jkube.docker.push.username` /
`jkube.docker.push.password` are used for pull and push operations,
respectively (when given). Either way, the standard lookup algorithm
as described in the previous section is used as fallback.

== Google Artifact Registry Authentication

link:https://cloud.google.com/artifact-registry/docs[Google Artifact Registry] is Google Cloud's container image registry service that requires authentication to push and pull container images.
The `{task-prefix}Push` and `{task-prefix}Build` tasks support several authentication methods for Google Artifact Registry.

For Artifact Registry repositories with URI like `us-central1-docker.pkg.dev/my-project/my-repo/my-image`, set `jkube.docker.registry` to `us-central1-docker.pkg.dev` and `my-project/my-repo/my-image` is the `name` of the image.

=== Authentication Methods

==== 1. Access Token Authentication (Recommended)

This method uses short-lived OAuth tokens (valid for 60 minutes) and provides the best balance between security and compatibility.

* Username: `oauth2accesstoken`
* Password: Output from `gcloud auth print-access-token`

.Example using system properties
[source,sh,subs="+attributes"]
----
gradle {task-prefix}Push \
  -Djkube.docker.username=oauth2accesstoken \
  -Djkube.docker.password="$(gcloud auth print-access-token)"
----

.Example using authConfig in build.gradle
[source,groovy,subs="attributes+"]
----
{pluginExtension} {
    authConfig {
        username = "oauth2accesstoken"
        password = System.getenv("GCLOUD_ACCESS_TOKEN")
    }
}
----

Then run:
[source,sh,subs="+attributes"]
----
export GCLOUD_ACCESS_TOKEN="$(gcloud auth print-access-token)"
gradle {task-prefix}Push
----

==== 2. Service Account Key Authentication

This method uses a service account JSON key file for authentication.

* Username: `_json_key`
* Password: Contents of the service account JSON key file

.Example using system properties
[source,sh,subs="+attributes"]
----
gradle {task-prefix}Push \
  -Djkube.docker.username=_json_key \
  -Djkube.docker.password="$(cat /path/to/key.json)"
----

.Example using authConfig in build.gradle
[source,groovy,subs="attributes+"]
----
{pluginExtension} {
    authConfig {
        username = "_json_key"
        password = new File("/path/to/key.json").text
    }
}
----

==== 3. Docker Credential Helper (docker-credential-gcr)

The standalone link:https://cloud.google.com/artifact-registry/docs/docker/authentication#standalone-helper[docker-credential-gcr helper] can be used for authentication and provides better performance than the gcloud CLI method.

After installing and configuring `docker-credential-gcr`, JKube will automatically use it when credentials are available through Docker's credential store.

.Installation
[source,sh]
----
gcloud components install docker-credential-gcr
docker-credential-gcr configure-docker
----

This configures `~/.docker/config.json` to use the credential helper, and JKube will automatically pick up the credentials.

[NOTE]
====
The access token method (option 1) is recommended for CI/CD pipelines and temporary access, as it provides short-lived credentials that are automatically rotated.
The service account key method (option 2) is useful for long-running services or when you need programmatic access without user interaction.
The credential helper method (option 3) provides the best developer experience for local development.
====