
[[enrichers]]
= Enrichers

Enriching is the complementary concept to <<generators, Generators>>. Whereas Generators are used to create and customize Docker images, Enrichers are use to create and customize {cluster} resource objects.

There are a lot of similarities to Generators:

* Each Enricher has a unique name.
* Enrichers are looked up automatically from the plugin dependencies and there is a set of default enrichers delivered with this plugin.
* Enrichers are configured the same ways as generators

The <<generator-example,Generator example>> is a good blueprint, simply replace `generator` with `enricher`. The configuration is structural identical:

.Enricher configuration
[cols="2,6"]
|===
| Element | Description

| `includes`
| Contains one ore more `include` elements with enricher names which should be included. If given, only this list of enrichers are included in this order. The enrichers from every active profile are included, too. However the enrichers listed here are moved to the front of the list, so that they are called first. Use the profile `raw` if you want to explicitly set the complete list of enrichers.

| `excludes`
| Holds one or more `exclude` elements with enricher names to exclude. This means all the detected enrichers are used except the ones mentioned in this section.

| `config`
| Configuration for all enrichers. Each enricher supports a specific set of configuration values as described in its documentation. The subelements of this section are enricher names. E.g. for enricher `jkube-service`, the sub-element is called `jkube-service`. This element then holds the specific enricher configuration like `name` for the service name. Configuration coming from profiles are merged into this config, but not overriding the configuration specified here.
|===

This plugin comes with a set of default enrichers. In addition custom enrichers can be easily added by providing implementation of the <<enricher-api, Enricher API>> and adding these as a dependency to the build.

[[enrichers-default]]
== Default Enrichers

{plugin} comes with a set of enrichers which are enabled by default. There are two categories of default enrichers:

* <<enrichers-generic, *Generic Enrichers*>> are used to add default resource object when they are missing or add common
  metadata extracted from the given build information.
* <<enrichers-specific, *Specific Enrichers*>> are enrichers which are focused on a certain tech stack that they detect.

.Default Enrichers Overview
[cols="2,7"]
|===
| Enricher | Description

| <<jkube-configmap-file>>
| Add ConfigMap elements defined as Groovy or as annotation.

|===

[[enrichers-generic]]
=== Generic Enrichers

Default generic enrichers are used for adding missing resources or adding metadata to given resource objects.
The following default enhancers are available out of the box.

include::enricher/_jkube_configmap_file.adoc[]

[[enrichers-specific]]
=== Specific Enrichers

Specific enrichers provide resource manifest enhancement for a certain tech stack that they detect.

// TODO - Add when support is complete
//== Enricher API

//_How to write your own enrichers and install them._
