[[generator-java-exec]]
=== Java Applications

One of the most generic _Generators_ is the `java-exec` generator.
It is responsible for starting up arbitrary Java application.
It knows how to deal with fat-jar applications where the application and all dependencies are included within a single jar and the `MANIFEST.MF` within the jar references a main class.
But also flat classpath applications, where the dependencies are separate jar files and a main class is given.

If no main class is explicitly configured, the plugin first attempts to locate a fat jar.
If the {plugin-type} build creates a JAR file with a `META-INF/MANIFEST.MF` containing a `Main-Class` entry, then this is considered to be the fat jar to use.
If there are more than one of such files then the largest one is used.

If a main class is configured (see below) then the image configuration will contain the application jar plus all dependency jars.
If no main class is configured as well as no fat jar being detected, then this _Generator_ tries to detect a single main class by searching for `public static void main(String args[])` among the application classes. If exactly one class is found this is considered to be the main class. If no or more than one is found the _Generator_ finally does nothing.

It will use the following base image by default, but as explained <<generator-options-common, above>> and can be changed with the `from` configuration.

[[generator-java-exec-from]]
.Java Base Images
[cols="1,4,4,4"]
|===
| | Docker Build | S2I Build | ImageStream

| *Default (latest)*
| `quay.io/jkube/jkube-java`
| `quay.io/jkube/jkube-java`
| `jkube-java`

| *Java 25*
| `quay.io/jkube/jkube-java-25`
| `quay.io/jkube/jkube-java-25`
| `jkube-java-25`

| *Java 21*
| `quay.io/jkube/jkube-java-21`
| `quay.io/jkube/jkube-java-21`
| `jkube-java-21`

| *Java 17*
| `quay.io/jkube/jkube-java-17`
| `quay.io/jkube/jkube-java-17`
| `jkube-java-17`

| *Java 11*
| `quay.io/jkube/jkube-java-11`
| `quay.io/jkube/jkube-java-11`
| `jkube-java-11`

|===

By default, the latest image is used. To select a specific Java version, see <<generator-java-exec-java-version>> below.

When a `fromMode` of `istag` is used to specify an `ImageStreamTag` and when no `from` is given, then as default the
`ImageStreamTag` `jkube-java` in the namespace `openshift` is chosen.
By default, `fromMode = "docker"` which use the a plain Docker image reference for the S2I builder image.

Beside the common configuration parameters described in the table <<generator-options-common, common generator options>>
the following additional configuration options are recognized:

[[generator-java-exec-options]]
.Java Application configuration options
[cols="1,6,1"]
|===
| Element | Description | Property

| *targetDir*
| Directory within the generated image where to put the detected artefacts into. Change this only if the base image is
  changed, too.

  Defaults to `/deployments`.
| `jkube.generator.java-exec.targetDir`

| *jolokiaPort*
| Port of the Jolokia agent exposed by the base image. Set this to 0 if you don't want to expose the Jolokia port.

  Defaults to `8778`.
| `jkube.generator.java-exec.jolokiaPort`

| *mainClass*
| Main class to call. If not given first a check is performed to detect a fat-jar (see above).

ifeval::["{plugin-type}" == "maven"]
Next a class is looked up by scanning `target/classes` for a single class with a main method.
endif::[]
ifeval::["{plugin-type}" == "gradle"]
Next a class is looked up by scanning `build/classes` for a single class with a main method.
endif::[]

If no such class is found or if more than one is
  found, then this generator does nothing.
| `jkube.generator.java-exec.mainClass`

| *prometheusPort*
| Port of the Prometheus jmx_exporter exposed by the base image. Set this to 0 if you don't want to expose the Prometheus
  port.

  Defaults to `9779`.
| `jkube.generator.java-exec.prometheusPort`

| *webPort*
| Port to expose as service, which is supposed to be the port of a web application. Set this to 0 if you don't want to
  expose a port.

  Defaults to `8080`.
| `jkube.generator.java-exec.webPort`
|===

The exposed ports are typically later on use by <<enrichers, Enrichers>> to create default Kubernetes or OpenShift services.

[[generator-java-exec-java-version]]
==== Selecting a specific Java version

By default, JKube uses the `jkube-java` base image which always tracks the latest supported Java version.
To pin a specific Java version for your base image, set the `jkube.java.version` property to one of the supported values: `11`, `17`, `21`, `25`.

ifeval::["{plugin-type}" == "maven"]
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<properties>
  <jkube.java.version>21</jkube.java.version>
</properties>
----

Or via the command line:

----
mvn package k8s:build -Djkube.java.version=21
----
endif::[]

ifeval::["{plugin-type}" == "gradle"]
In `gradle.properties`:

[source,properties,indent=0,subs="verbatim,quotes,attributes"]
----
jkube.java.version=21
----

Or via the command line:

----
gradle k8sBuild -Pjkube.java.version=21
----
endif::[]

This property works across all Java-based generators (java-exec, Spring Boot, Quarkus, Micronaut, Helidon, Vert.x, WildFly JAR, Open Liberty).

.Precedence
If both `from` and `jkube.java.version` are configured, `from` takes precedence and a warning is emitted.
Setting an unsupported value will cause the build to fail with a message listing the supported versions.

You can add additional files to the target image within `baseDir` by placing files into `src/main/jkube-includes`.
These will be added with mode `0644`, while everything in `src/main/jkube-includes/bin` will be added with `0755`.
