[[generator-webapp]]
=== Web Applications
ifeval::["{goal-prefix}" == "oc"]
:doc-openshift:
endif::[]
ifeval::["{task-prefix}" == "oc"]
:doc-openshift:
endif::[]
ifeval::["{plugin-type}" == "maven"]
The `webapp` generator tries to detect WAR builds and selects a base servlet container image based on the configuration found in the `pom.xml`:

* A **Tomcat** base image is selected when a `tomcat6-maven-plugin`,
`tomcat7-maven-plugin` or `tomcat8-maven-plugin` is present or when a `META-INF/context.xml` could be found in the classes directory.
* A **Jetty** base image is selected when a `jetty-maven-plugin` is present or one of the files `WEB-INF/jetty-web.xml` or `WEB-INF/jetty-logging.properties` is found.
* A **Wildfly** base image is chosen for a given `jboss-as-maven-plugin` or `wildfly-maven-plugin` or when a Wildfly specific deployment descriptor like `jboss-web.xml` is found.

endif::[]
ifeval::["{plugin-type}" == "gradle"]
The `webapp` generator tries to detect WAR builds and selects a base servlet container image based on the configuration found in the `build.gradle`:

* A **Tomcat** base image is selected by default.
* A **Jetty** base image is selected when one of the files `WEB-INF/jetty-web.xml` or `WEB-INF/jetty-logging.properties` is found.
* A **Wildfly** base image is chosen when a Wildfly specific deployment descriptor like `jboss-web.xml` is found.

endif::[]

The base images chosen are:

[[generator-webapp-from]]
.Webapp Base Images
[cols="1,4,4"]
|===
| | Docker Build | S2I Build

| *Tomcat*
| `quay.io/jkube/jkube-tomcat9`
| `quay.io/jkube/jkube-tomcat9`

| *Jetty*
| `quay.io/jkube/jkube-jetty9`
| `quay.io/jkube/jkube-jetty9`

| *Wildfly*
| `jboss/wildfly`
| https://github.com/wildfly/wildfly-s2i[`quay.io/wildfly/wildfly-centos7`]
|===

In addition to the  <<generator-options-common, common generator options>> this generator can be configured with the following options:

.Webapp configuration options
[cols="1,6,1"]
|===
| Element | Description | Property

| *server*
| Fix server to use in the base image. Can be either **tomcat**, **jetty** or **wildfly**.
| `jkube.generator.webapp.server`

| *targetDir*
| Where to put the war file into the target image. By default, it's selected by the base image chosen but can be
  overwritten with this option.

  Defaults to `/deployments`.
| `jkube.generator.webapp.targetDir`

| *user*
| User and/or group under which the files should be added. The syntax of this options is described in
  <<config-image-build-assembly, Assembly Configuration>>.
| `jkube.generator.webapp.user`

| *path*
| Context path with which the application can be reached by default.

  Defaults to `/` (root context).
| `jkube.generator.webapp.path`

| *cmd*
| Command to use to start the container. By default, the base images startup command is used.
| `jkube.generator.webapp.cmd`

| *ports*
| Comma separated list of ports to expose in the image and which eventually are translated later to Kubernetes services.
  The ports depend on the base image and are selected automatically. But they can be overridden here.
| `jkube.generator.webapp.ports`

| *env*
| Environment variable to be set to the image builder environment. Should be set in the format `ENV_NAME=environment value`. You can inject multiple env variables by adding a new line for each variable.

ifdef::doc-openshift[]
This may be required for Wildfly webapp s2i build to compose a `WildFly` server with Galleon layers. See https://docs.wildfly.org/21/Galleon_Guide.html#wildfly_foundational_galleon_layers and https://github.com/wildfly/wildfly-s2i#environment-variables-to-be-used-at-s2i-build-time/.
endif::[]
| `jkube.generator.webapp.env`
|===
