---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
      image.openshift.io/triggers: |-
        [ {
          "from" : {
            "kind" : "ImageStreamTag",
            "name" : "triggersannotation:latest"
          },
          "fieldPath" : "spec.template.spec.containers[?(@.name==\"orgeclipsejkubeintegrationtestsgradle-triggersannotation\")].image"
        } ]
    labels:
      app: triggersannotation
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: triggersannotation
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: triggersannotation
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: triggersannotation
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: triggersannotation:latest
          imagePullPolicy: IfNotPresent
          name: orgeclipsejkubeintegrationtestsgradle-triggersannotation
          securityContext:
            privileged: false
