---
apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: serviceaccount-via-groovy-dsl
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: serviceaccount-via-groovy-dsl
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: serviceaccount-via-groovy-dsl
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          app.openshift.io/vcs-ref: "@ignore@"
          jkube.io/git-url: "@ignore@"
          app.openshift.io/vcs-uri: "@ignore@"
          jkube.io/git-commit: "@ignore@"
          jkube.io/git-branch: "@ignore@"
        labels:
          app: serviceaccount-via-groovy-dsl
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
        name: serviceaccount-via-groovy-dsl
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: repository/serviceaccount-via-groovy-dsl:latest
          imagePullPolicy: IfNotPresent
          name: repository-serviceaccount-via-groovy-dsl
          securityContext:
            privileged: false
        serviceAccountName: my-serviceaccount
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - repository-serviceaccount-via-groovy-dsl
        from:
          kind: ImageStreamTag
          name: serviceaccount-via-groovy-dsl:latest
      type: ImageChange
