---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: well-known-labels
      app.kubernetes.io/version: "@ignore@"
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app: "well-known-labels"
      provider: "jkube"
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: well-known-labels
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: "well-known-labels"
      provider: "jkube"
      group: org.eclipse.jkube.integration.tests.gradle
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: well-known-labels
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: well-known-labels
      app.kubernetes.io/version: "@ignore@"
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app: "well-known-labels"
      provider: "jkube"
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: well-known-labels
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: "well-known-labels"
        provider: "jkube"
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: well-known-labels
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: "well-known-labels"
          provider: "jkube"
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
          app.kubernetes.io/managed-by: jkube
          app.kubernetes.io/name: well-known-labels
          app.kubernetes.io/version: "@ignore@"
          app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: repository/well-known-labels:latest
          imagePullPolicy: IfNotPresent
          name: repository-well-known-labels
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          securityContext:
            privileged: false
