#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: java-options-env-merge
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    template:
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: valueFromImage valueFromResources
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: test:latest
          imagePullPolicy: IfNotPresent
          name: orgeclipsejkubeintegrationtestsgradle-java-options-env-merge
          securityContext:
            privileged: false
