---
apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@assertThat(not(isEmptyString())@"
      jkube.eclipse.org/git-url: "@matches('(?:git|ssh|https?|git@[-\\w.]+):(\\/\\/)?(.*?)(\\.git)(\\/?|\\#[-\\d\\w._]+?)$')@"
      app.openshift.io/vcs-uri: "@matches('(?:git|ssh|https?|git@[-\\w.]+):(\\/\\/)?(.*?)(\\.git)(\\/?|\\#[-\\d\\w._]+?)$')@"
      jkube.eclipse.org/git-commit: "@matches('\\b[0-9a-f]{5,40}\\b')@"
      jkube.eclipse.org/git-branch: "@assertThat(not(isEmptyString())@"
    labels:
      app: git-annotations
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: git-annotations
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: git-annotations
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          app.openshift.io/vcs-ref: "@assertThat(not(isEmptyString())@"
          jkube.eclipse.org/git-url: "@matches('(?:git|ssh|https?|git@[-\\w.]+):(\\/\\/)?(.*?)(\\.git)(\\/?|\\#[-\\d\\w._]+?)$')@"
          app.openshift.io/vcs-uri: "@matches('(?:git|ssh|https?|git@[-\\w.]+):(\\/\\/)?(.*?)(\\.git)(\\/?|\\#[-\\d\\w._]+?)$')@"
          jkube.eclipse.org/git-commit: "@matches('\\b[0-9a-f]{5,40}\\b')@"
          jkube.eclipse.org/git-branch: "@assertThat(not(isEmptyString())@"
        labels:
          app: git-annotations
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: repository/git-annotations:latest
          imagePullPolicy: IfNotPresent
          name: repository-git-annotations
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - repository-git-annotations
        from:
          kind: ImageStreamTag
          name: git-annotations:latest
      type: ImageChange
