---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: smallrye-health
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: smallrye-health
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: smallrye-health
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: smallrye-health
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: smallrye-health
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: smallrye-health
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.io/git-url: "@ignore@"
          jkube.io/git-commit: "@ignore@"
          jkube.io/git-branch: "@ignore@"
        labels:
          app: smallrye-health
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
        name: smallrye-health
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: gradle/smallrye-health:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
          name: webapp
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
