#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      testProject: spring-boot-sample
      provider: jkube
      app: jkube-maven-sample-spring-boot
      version: "@ignore@"
      group: org.eclipse.jkube
    name: jkube-maven-sample-spring-boot
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: jkube-maven-sample-spring-boot
      provider: jkube
      group: org.eclipse.jkube
    type: NodePort
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      testProject: spring-boot-sample
      provider: jkube
      app: jkube-maven-sample-spring-boot
      version: "@ignore@"
      group: org.eclipse.jkube
    name: jkube-maven-sample-spring-boot
  spec:
    replicas: 1
    selector:
      app: jkube-maven-sample-spring-boot
      provider: jkube
      group: org.eclipse.jkube
    template:
      metadata:
        labels:
          testProject: spring-boot-sample
          provider: jkube
          app: jkube-maven-sample-spring-boot
          version: "@ignore@"
          group: org.eclipse.jkube
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: jkube-maven-sample-spring-boot:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
