FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8-860
EXPOSE 8082
COPY /jkube-generated-layer-original/opt/deployments /opt/deployments/
COPY /jkube-generated-layer-final-artifact/opt/deployments /opt/deployments/
ENTRYPOINT java -jar /opt/deployments/xml-image-multilayer-0.1-SNAPSHOT.jar
