---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /metrics
      jkube.eclipse.org/git-branch: "@ignore@"
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
    labels:
      app: probes-groovy-dsl-config
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.it.gradle.probes.groovy.dsl
    name: probes-groovy-dsl-config
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: probes-groovy-dsl-config
      provider: jkube
      group: org.eclipse.jkube.it.gradle.probes.groovy.dsl
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: probes-groovy-dsl-config
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.it.gradle.probes.groovy.dsl
    name: probes-groovy-dsl-config
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: probes-groovy-dsl-config
        provider: jkube
        group: org.eclipse.jkube.it.gradle.probes.groovy.dsl
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: probes-groovy-dsl-config
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.it.gradle.probes.groovy.dsl
        name: probes-groovy-dsl-config
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: dsl/probes-groovy-dsl-config:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
          startupProbe:
            failureThreshold: 1
            httpGet:
              host: ""
              path: /liveness/startup
              port: 8080
              scheme: HTTP
            periodSeconds: 30
