---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9779"
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        app.openshift.io/vcs-ref: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: multi-env-same-kind-profile-overridden
        provider: jkube
        version: 0.1-SNAPSHOT
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: multi-env-same-kind-profile-overridden
        app.kubernetes.io/version: 0.1-SNAPSHOT
      name: multi-env-same-kind-profile-overridden
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: multi-env-same-kind-profile-overridden
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/name: multi-env-same-kind-profile-overridden
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        app.openshift.io/vcs-ref: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: multi-env-same-kind-profile-overridden
        provider: jkube
        version: 0.1-SNAPSHOT
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: multi-env-same-kind-profile-overridden
        app.kubernetes.io/version: 0.1-SNAPSHOT
      name: multi-env-same-kind-profile-overridden
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: multi-env-same-kind-profile-overridden
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/name: multi-env-same-kind-profile-overridden
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          annotations:
            jkube.eclipse.org/git-commit: "@ignore@"
            jkube.eclipse.org/git-url: "@ignore@"
            app.openshift.io/vcs-ref: "@ignore@"
            app.openshift.io/vcs-uri: "@ignore@"
            jkube.eclipse.org/git-branch: "@ignore@"
          labels:
            app: multi-env-same-kind-profile-overridden
            provider: jkube
            version: 0.1-SNAPSHOT
            group: org.eclipse.jkube.integration.tests.gradle
            app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
            app.kubernetes.io/managed-by: jkube
            app.kubernetes.io/name: multi-env-same-kind-profile-overridden
            app.kubernetes.io/version: 0.1-SNAPSHOT
          name: multi-env-same-kind-profile-overridden
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: multi-env-same-kind-profile-overridden:latest
              imagePullPolicy: IfNotPresent
              name: spring-boot
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                - containerPort: 9779
                  name: prometheus
                  protocol: TCP
                - containerPort: 8778
                  name: jolokia
                  protocol: TCP
              securityContext:
                privileged: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - spring-boot
            from:
              kind: ImageStreamTag
              name: multi-env-same-kind-profile-overridden:latest
          type: ImageChange
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        cert-manager.io/issuer-name: letsencrypt-common
        haproxy.router.openshift.io/timeout: 120s
        cert-manager.io/issuer-kind: ClusterIssuer
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        app.openshift.io/vcs-ref: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: multi-env-same-kind-profile-overridden
        provider: jkube
        version: 0.1-SNAPSHOT
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: multi-env-same-kind-profile-overridden
        app.kubernetes.io/version: 0.1-SNAPSHOT
      name: multi-env-same-kind-profile-overridden
      namespace: demo-namespace
    spec:
      host: demoapp.apps.example.com
      port:
        targetPort: http
      tls:
        insecureEdgeTerminationPolicy: Allow
        termination: dev-overridden
      to:
        kind: Service
        name: multi-env-same-kind-profile-overridden
