.Example of Controller Resource Configuration
[source,xml]
----
<configuration>
    <resources>
        <controller>
            <env> <!--1-->
              <organization>Eclipse Foundation</organization>
              <projectname>jkube</projectname>
            </env>
            <controllerName>my-deploymentname</controllerName> <!--2-->
            <containerPrivileged>true</containerPrivileged> <!--3-->
            <imagePullPolicy>Always</imagePullPolicy> <!--4-->
            <replicas>3</replicas> <!--5-->
            <liveness> <!--6-->
                <getUrl>http://:8080/q/health</getUrl>
                <tcpPort>8080</tcpPort>
                <initialDelaySeconds>3</initialDelaySeconds>
                <timeoutSeconds>3</timeoutSeconds>
            </liveness>
            <startup> <!--7-->
                <periodSeconds>30</periodSeconds>
                <failureThreshold>1</failureThreshold>
                <getUrl>http://:8080/actuator/health</getUrl>
            </startup>
            <volumes> <!--8-->
              <volume>
                <name>scratch</name>
                <type>emptyDir</type>
                <medium>Memory</medium>
                <mounts>
                  <mount>/var/scratch</mount>
                </mounts>
              </volume>
            </volumes>
           <containerResources>
              <requests> <!--9-->
                 <memory>32Mi</memory>
                 <cpu>300m</cpu>
              </requests>
              <limits> <!--10-->
                 <memory>64Mi</memory>
                 <cpu>500m</cpu>
              </limits>
           </containerResources>
        </controller>
    </resources>
</configuration>
----

<1> Environment variables added to all of your application Pods
<2> Name of Controller(`metadata.name` set in generated Deployment, Job, ReplicaSet etc)
<3> Setting https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod[Security Context] of all application Pods.
<4> Configure how images would be updated. Can be one of `IfNotPresent`, `Always` or `Never`. Read https://kubernetes.io/docs/concepts/containers/images/#updating-images[Kubernetes Images docs] for more details.
<5> Number of replicas of pods we want to have in our application
<6> Define an HTTP liveness request, see https://kubernetes.io/docs/concepts/containers/images/#updating-images[Kubernetes Liveness/Readiness probes] for more details.
<7> Define an HTTP startup request, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/[Kubernetes Startup probes] for more details.
<8> Mounting an EmptyDir Volume to your application pods
<9> Requests describe the minimum amount of compute resources required. See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[Kubernetes Resource Management Documentation] for more info.
<10> Limits describe the maximum amount of compute resources allowed. See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[Kubernetes Resource Management Documentation] for more info.
