---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      jkube.io/git-branch: "@ignore@"
      jkube.io/iconUrl: https://cdn.rawgit.com/jkubeio/jkube-devops/master/jkube-docker-registry/src/main/jkube/icon.png
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
    labels:
      app: volume-permission
      provider: jkube
      version: "@ignore@"
      expose: "true"
      group: org.eclipse.jkube.devops.apps
    name: jkube-docker-registry
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: jkube-docker-registry
      provider: jkube
      group: org.eclipse.jkube.devops.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: volume-permission
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: jkube-docker-registry-storage
  spec:
    storageClassName: cheese
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      jkube.io/iconUrl: https://cdn.rawgit.com/jkubeio/jkube-devops/master/jkube-docker-registry/src/main/jkube/icon.png
    labels:
      app: volume-permission
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.devops.apps
    name: jkube-docker-registry
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      provider: jkube
      app: volume-permission
      group: org.eclipse.jkube.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          jkube.io/iconUrl: https://cdn.rawgit.com/jkubeio/jkube-devops/master/jkube-docker-registry/src/main/jkube/icon.png
        labels:
          app: volume-permission
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.devops.apps
        name: volume-permission
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: registry:2
          imagePullPolicy: IfNotPresent
          name: jkube-docker-registry
          ports:
          - containerPort: 5000
            name: http
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /var/lib/registry
            name: jkube-docker-registry-storage
            readOnly: false
        initContainers:
        - command:
          - chmod
          - "777"
          - /var/lib/registry
          image: busybox
          imagePullPolicy: IfNotPresent
          name: jkube-volume-permission
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
          volumeMounts:
          - mountPath: /var/lib/registry
            name: jkube-docker-registry-storage
        volumes:
        - name: jkube-docker-registry-storage
          persistentVolumeClaim:
            claimName: jkube-docker-registry-storage
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jkube-docker-registry
        from:
          kind: ImageStreamTag
          name: registry:2
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      jkube.io/git-branch: "@ignore@"
      jkube.io/iconUrl: https://cdn.rawgit.com/jkubeio/jkube-devops/master/jkube-docker-registry/src/main/jkube/icon.png
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
    labels:
      app: volume-permission
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.devops.apps
    name: jkube-docker-registry
  spec:
    port:
      targetPort: 80
    to:
      kind: Service
      name: jkube-docker-registry
