#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: vertx-default-sample
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: vertx-default-sample
      provider: jkube
      group: io.jkube
- apiVersion: apps/v1 
  kind: Deployment
  metadata:
    labels:
      provider: jkube
      app: vertx-default-sample
      version: "@ignore@"
      group: io.jkube
    name: vertx-default-sample
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vertx-default-sample
        provider: jkube
        group: io.jkube
    template:
      metadata:
        labels:
          provider: jkube
          app: vertx-default-sample
          version: "@ignore@"
          group: io.jkube
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: "@matches('jkube/vertx-default-sample:.*$')@"
          imagePullPolicy: IfNotPresent
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
