#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    jkube.eclipse.org/iconUrl: "https://cdn.rawgit.com/jkubeio/jkube-devops/master/jkube-docker-registry/src/main/jkube/icon.png"
  labels:
    provider: "jkube"
    app: "${project.artifactId}"
    version: "${project.version}"
    group: "org.eclipse.jkube.devops.apps"
  name: "jkube-docker-registry"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      provider: "jkube"
      app: "${project.artifactId}"
      group: "org.eclipse.jkube.devops.apps"
  template:
    metadata:
      labels:
        provider: "jkube"
        app: "${project.artifactId}"
        version: "${project.version}"
        group: "org.eclipse.jkube.devops.apps"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "registry:2"
        imagePullPolicy: "IfNotPresent"
        name: "jkube-docker-registry"
        ports:
        - containerPort: 5000
          name: "http"
        volumeMounts:
        - mountPath: /var/lib/registry
          name: jkube-docker-registry-storage
          readOnly: false
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
      - name: "jkube-docker-registry-storage"
        persistentVolumeClaim:
          claimName: jkube-docker-registry-storage
