---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: expose
      app.kubernetes.io/version: "@ignore@"
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app: expose
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: expose
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    selector:
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: expose
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app: expose
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: expose
      app.kubernetes.io/version: "@ignore@"
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app: expose
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: expose
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: expose
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app: expose
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app.kubernetes.io/managed-by: jkube
          app.kubernetes.io/name: expose
          app.kubernetes.io/version: "@ignore@"
          app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
          app: expose
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
        name: expose
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: repository/expose:latest
          imagePullPolicy: IfNotPresent
          name: repository-expose
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          securityContext:
            privileged: false
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: expose
      app.kubernetes.io/version: "@ignore@"
      app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
      app: expose
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: expose
  spec:
    defaultBackend:
      service:
        name: expose
        port:
          number: 80
