---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: serviceaccounts-via-groovy-dsl
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: my-serviceaccount
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: serviceaccounts-via-groovy-dsl
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: serviceaccounts-via-groovy-dsl
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: serviceaccounts-via-groovy-dsl
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: serviceaccounts-via-groovy-dsl
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: repository/serviceaccounts-via-groovy-dsl:latest
          imagePullPolicy: IfNotPresent
          name: repository-serviceaccounts-via-groovy-dsl
          securityContext:
            privileged: false
        serviceAccountName: my-serviceaccount
