---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: helm-complex-values
        provider: jkube
        version:  "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: helm-complex-values
      annotations:
        example.org/env: dev
        example.org/kind: ServiceDev
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: helm-complex-values
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: helm-complex-values
        provider: jkube
        version:  "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: helm-complex-values
      annotations:
        example.org/env: dev
        example.org/kind: DeploymentDev
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: helm-complex-values
          provider: jkube
          group: org.eclipse.jkube.integration.tests.gradle
      template:
        metadata:
          annotations: "@ignore@"
          labels:
            app: helm-complex-values
            provider: jkube
            version:  "@ignore@"
            group: org.eclipse.jkube.integration.tests.gradle
        spec:
          hostAliases:
          - hostnames:
            - dev.example.com
            ip: 127.0.0.1
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: repository/helm:latest
              imagePullPolicy: IfNotPresent
              name: repository-helm-complex-values
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              securityContext:
                privileged: false
