---
replicaCount: 1
common:
  annotations:
    example.org/one: one
    example.org/two: two
    example.org/env: prod
deployment:
  annotations:
    example.org/kind: Deployment
  hostAliases:
    - ip: 1.1.1.1
      hostnames:
        - one.example.com
    - ip: 1.1.1.2
      hostnames:
        - two.example.com
service:
  annotations:
    example.org/kind: Service
