#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: jkube-maven-sample-dependency-resources-dependent
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube
      app.kubernetes.io/name: jkube-maven-sample-dependency-resources-dependent
      app.kubernetes.io/version: "@ignore@"
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/part-of: org.eclipse.jkube
    name: example
  spec:
    replicas: 1337
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: jkube-maven-sample-dependency-resources-dependent
        provider: jkube
        group: org.eclipse.jkube
        app.kubernetes.io/name: jkube-maven-sample-dependency-resources-dependent
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/part-of: org.eclipse.jkube
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: jkube-maven-sample-dependency-resources-dependent
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube
          app.kubernetes.io/name: jkube-maven-sample-dependency-resources-dependent
          app.kubernetes.io/version: "@ignore@"
          app.kubernetes.io/managed-by: jkube
          app.kubernetes.io/part-of: org.eclipse.jkube
      spec:
        containers:
        - env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: busybox
          name: jkube-maven-sample-dependency-resources-dependent
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      jkube.eclipse.org/git-branch: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-url: "@ignore@"
    labels:
      env: dev
      role: web
    name: web
  spec:
    replicas: 1337
    selector:
      matchLabels:
        role: web
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-branch: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-url: "@ignore@"
        labels:
          role: web
      spec:
        containers:
          - image: nginx
            name: nginx
