---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        app.openshift.io/vcs-ref: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: image-pull-secrets
        provider: jkube
        version: 0.0.1-SNAPSHOT
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: image-pull-secrets
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
      name: image-pull-secrets
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: image-pull-secrets
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/name: image-pull-secrets
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        app.openshift.io/vcs-ref: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: image-pull-secrets
        provider: jkube
        version: 0.0.1-SNAPSHOT
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: image-pull-secrets
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
      name: image-pull-secrets
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: image-pull-secrets
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/name: image-pull-secrets
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          annotations:
            jkube.eclipse.org/git-commit: "@ignore@"
            jkube.eclipse.org/git-url: "@ignore@"
            app.openshift.io/vcs-ref: "@ignore@"
            app.openshift.io/vcs-uri: "@ignore@"
            jkube.eclipse.org/git-branch: "@ignore@"
          labels:
            app: image-pull-secrets
            provider: jkube
            version: 0.0.1-SNAPSHOT
            group: org.eclipse.jkube.integration.tests.gradle
            app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
            app.kubernetes.io/managed-by: jkube
            app.kubernetes.io/name: image-pull-secrets
            app.kubernetes.io/version: 0.0.1-SNAPSHOT
          name: image-pull-secrets
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: repository/image-pull-secrets:latest
              imagePullPolicy: IfNotPresent
              name: repository-image-pull-secrets
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              securityContext:
                privileged: false
          imagePullSecrets:
            - name: secret-1
            - name: secret-2
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - repository-image-pull-secrets
            from:
              kind: ImageStreamTag
              name: image-pull-secrets:latest
          type: ImageChange
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-url: "@ignore@"
        app.openshift.io/vcs-ref: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: image-pull-secrets
        provider: jkube
        version: 0.0.1-SNAPSHOT
        group: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/part-of: org.eclipse.jkube.integration.tests.gradle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: image-pull-secrets
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
      name: image-pull-secrets
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: image-pull-secrets
