---
apiVersion: v1
kind: List
items:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      annotations:
        jkube.eclipse.org/git-url: "@ignore@"
        jkube.eclipse.org/git-commit: "@ignore@"
        jkube.eclipse.org/git-branch: "@ignore@"
      labels:
        app: controller
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: controller
    spec:
      template:
        metadata:
          labels:
            app: controller
            provider: jkube
            version: "@ignore@"
            group: org.eclipse.jkube.integration.tests.gradle
        spec:
          restartPolicy: OnFailure
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: repository/controller:latest
              imagePullPolicy: IfNotPresent
              name: repository-controller
              securityContext:
                privileged: false
