---
apiVersion: v1
kind: List
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      jkube.eclipse.org/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: controller
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: controller
  spec:
    template:
      metadata:
        labels:
          app: controller
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        restartPolicy: OnFailure
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: repository/controller:latest
          imagePullPolicy: IfNotPresent
          name: repository-controller
          securityContext:
            privileged: false
