
[[jkube-maven-scm-enricher]]
==== jkube-maven-scm-enricher

This enricher adds additional https://maven.apache.org/pom.html#SCM[SCM] related metadata to all objects supporting annotations.
These metadata will be added only if https://maven.apache.org/pom.html#SCM[SCM] information is present in the maven `pom.xml` of the project.

The following annotations will be added to the objects that supports annotations,

.Maven SCM Enrichers Annotation Mapping
[cols="2,2,3"]
|===
| Maven SCM Info | Annotation | Description

| scm/connection
| jkube.eclipse.org/scm-con-url
| The SCM connection that will be used to connect to the project's SCM

| scm/developerConnection
| jkube.eclipse.org/scm-devcon-url
| The SCM Developer Connection that will be used to connect to the project's developer SCM

| scm/tag
| jkube.eclipse.org/scm-tag
| The SCM tag that will be used to checkout the sources, like HEAD dev-branch etc.,

| scm/url
| jkube.eclipse.org/scm-url
| The SCM web url that can be used to browse the SCM over web browser

| scm/connection
| jkube.io/scm-con-url
| _Deprecated: Use `jkube.eclipse.org/` annotation prefix._

The SCM connection that will be used to connect to the project's SCM

| scm/developerConnection
| jkube.io/scm-devcon-url
| _Deprecated: Use `jkube.eclipse.org/` annotation prefix._

The SCM Developer Connection that will be used to connect to the project's developer SCM

| scm/tag
| jkube.io/scm-tag
| _Deprecated: Use `jkube.eclipse.org/` annotation prefix._

The SCM tag that will be used to checkout the sources, like HEAD dev-branch etc.,

| scm/url
| jkube.io/scm-url
| _Deprecated: Use `jkube.eclipse.org/` annotation prefix._

The SCM web url that can be used to browse the SCM over web browser

|===

Lets say you have a maven pom.xml with the following scm information,
[source,xml]
----
<scm>
    <connection>scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git</connection>
    <developerConnection>scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git</developerConnection>
    <url>git://github.com/jkubeio/kubernetes-maven-plugin.git</url>
</scm>

----
This information will be enriched as annotations in the generated manifest like,

[source,yaml]
----
# ...
  kind: Service
  metadata:
    annotations:
      jkube.eclipse.org/scm-con-url: "scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git"
      jkube.eclipse.org/scm-devcon-url: "scm:git:git://github.com/jkubeio/kubernetes-maven-plugin.git"
      jkube.eclipse.org/scm-tag: "HEAD"
      jkube.eclipse.org/scm-url: "git://github.com/jkubeio/kubernetes-maven-plugin.git"
# ...
----
