*Adding {plugin} to project*

You would need to add {plugin} to your project in order to use it:

include::_add_plugin.adoc[]

ifeval::["{goal-prefix}" == "k8s"]
include::_build_push_scenario.adoc[]
endif::[]
ifeval::["{task-prefix}" == "k8s"]
include::_build_push_scenario.adoc[]
endif::[]

ifeval::["{task-prefix}" == "oc"]
include::_openshift_build_scenario.adoc[]
endif::[]
ifeval::["{goal-prefix}" == "oc"]
include::_openshift_build_scenario.adoc[]
endif::[]

*Generating & applying Kubernetes manifests*

Just like container image, {plugin} can generate opinionated {cluster} manifests. Run this command to automatically generate and apply manifests onto currently logged in {cluster} cluster.


ifeval::["{plugin-type}" == "maven"]
[source,sh,subs="attributes+"]
----
$ ./mvnw {goal-prefix}:resource {goal-prefix}:apply
----

After running these goals, you can also check {cluster} manifests generated by {plugin} in `target/classes/META-INF/jkube/` directory.
endif::[]

ifeval::["{plugin-type}" == "gradle"]
[source,sh,subs="attributes+"]
----
$ ./gradlew {task-prefix}Resource {task-prefix}Apply
----

After running these tasks, you can also check {cluster} manifests generated by {plugin} in `build/classes/java/main/META-INF/jkube/` directory.
endif::[]

Cleanup applied Kubernetes resources after testing:


ifeval::["{plugin-type}" == "maven"]
[source,sh,subs="attributes+"]
----
$ ./mvnw {goal-prefix}:undeploy
----
endif::[]

ifeval::["{plugin-type}" == "gradle"]
[source,sh,subs="attributes+"]
----
$ ./gradlew {task-prefix}Undeploy
----
endif::[]