[[vertx-scenario]]
== Vert.x

You can easily get started with using {plugin} on an https://start.vertx.io/[Eclipse Vert.x] without providing any explicit configuration. {plugin} would generate an opinionated container image and manifests by inspecting your project configuration.

include::_generic_gettingstarted_scenario.adoc[]

*How to set Service Port?*

By default, in Vert.x applications, application port value is 8888. {plugin} opinionated defaults use port 8080. If you want to change this, you'll need to configure {plugin} to generate image with desired port:

ifeval::["{plugin-type}" == "maven"]
[source,xml,subs="attributes+"]
----
<configuration>
  <generator>
    <config>
      <vertx>
        <webPort>8080</webPort>
      </vertx>
    </config>
  </generator>
</configuration>
----
endif::[]

ifeval::["{plugin-type}" == "gradle"]
.Example for setting port number for vertx apps
[source,groovy,subs="attributes+"]
----
{pluginExtension} {
  generator {
      config {
          'vertx' {
              webPort = '8888'
          }
      }
  }
}
----
endif::[]

Once configured, you can go ahead and deploy application to {cluster}.

*How to add Kubernetes Readiness Liveness probes?*

{plugin} doesn't add any {cluster} liveness and readiness probes by default. However, it does provide a rich set of configuration options to add health checks. Read <<jkube-healthcheck-vertx, Vert.x Healthchecks>> section for more details.
