---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      expose: "true"
      app: service
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: svc1
  spec:
    ports:
    - name: port1
      nodePort: 301243
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: service
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: service
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: svc2
  spec:
    clusterIP: None
    ports:
    - name: port2
      port: 8081
      protocol: TCP
      targetPort: 0
    selector:
      app: service
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.io/git-url: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      jkube.io/git-branch: "@ignore@"
    labels:
      app: service
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: service
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: service
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.io/git-url: "@ignore@"
          jkube.io/git-commit: "@ignore@"
          jkube.io/git-branch: "@ignore@"
        labels:
          app: service
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: repository/service:latest
          imagePullPolicy: IfNotPresent
          name: repository-service
          securityContext:
            privileged: false
