#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      provider: jkube
      app: jkube-maven-sample-remote-resources
      version: "@ignore@"
      group: org.eclipse.jkube
    name: jkube-maven-sample-remote-resources
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: jkube-maven-sample-remote-resources
      provider: jkube
      group: org.eclipse.jkube
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      provider: jkube
      app: jkube-maven-sample-remote-resources
      version: "@ignore@"
      group: org.eclipse.jkube
    name: jkube-maven-sample-remote-resources
  spec:
    replicas: 1
    selector:
      app: jkube-maven-sample-remote-resources
      provider: jkube
      group: org.eclipse.jkube
    template:
      metadata:
        labels:
          provider: jkube
          app: jkube-maven-sample-remote-resources
          version: "@ignore@"
          group: org.eclipse.jkube
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Dvertx.cacheDirBase=/tmp/vertx-cache -Dvertx.disableDnsResolver=true -Dvertx.metrics.options.enabled=true
              -Dvertx.metrics.options.jmxEnabled=true -Dvertx.metrics.options.jmxDomain=vertx
              -Xmx1500m
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: "@ignore@"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
