---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        keyinserviceaccount: valueinserviceaccount
        keyinall: valueinall
      labels:
        keyinserviceaccount: valueinserviceaccount
        keyinall: valueinall
        app: metadata
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: test-serviceaccount
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        jkube.io/git-url: "@ignore@"
        jkube.io/git-commit: "@ignore@"
        keyinall: valueinall
        jkube.io/git-branch: "@ignore@"
        keyinservice: valueinservice
      labels:
        keyinall: valueinall
        keyinservice: valueinservice
        app: metadata
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: metadata
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: metadata
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        keyiningress: valueiningress
        jkube.io/git-url: "@ignore@"
        jkube.io/git-commit: "@ignore@"
        keyinall: valueinall
        jkube.io/git-branch: "@ignore@"
      labels:
        keyiningress: valueiningress
        keyinall: valueinall
        app: metadata
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: metadata
    spec:
      defaultBackend:
        service:
          name: metadata
          port:
            number: 8080
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      annotations:
        keyinreplicaset: valueinreplicaset
        jkube.io/git-url: "@ignore@"
        jkube.io/git-commit: "@ignore@"
        keyinall: valueinall
        jkube.io/git-branch: "@ignore@"
        image.openshift.io/triggers: "@ignore@"
      labels:
        keyinall: valueinall
        keyinreplicaset: valueinreplicaset
        app: metadata
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: metadata
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: metadata
          provider: jkube
          group: org.eclipse.jkube.integration.tests.gradle
      template:
        metadata:
          annotations:
            keyinpodtemplate: valueinpodtemplate
            keyinall: valueinall
          labels:
            keyinpodtemplate: valueinpodtemplate
            keyinall: valueinall
            app: metadata
            provider: jkube
            version: "@ignore@"
            group: org.eclipse.jkube.integration.tests.gradle
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: repository/metadata:latest
              imagePullPolicy: IfNotPresent
              name: repository-metadata
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              securityContext:
                privileged: false
