---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      keyinserviceaccount: valueinserviceaccount
      keyinall: valueinall
    labels:
      keyinserviceaccount: valueinserviceaccount
      keyinall: valueinall
      app: metadata
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: test-serviceaccount
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      keyinall: valueinall
      jkube.io/git-branch: "@ignore@"
      keyinservice: valueinservice
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
    labels:
      keyinall: valueinall
      keyinservice: valueinservice
      app: metadata
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: metadata
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: metadata
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      keyinall: valueinall
      jkube.io/git-branch: "@ignore@"
      keyindeployment: valueindeployment
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
    labels:
      keyindeployment: valueindeployment
      keyinall: valueinall
      app: metadata
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: metadata
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: metadata
      provider: jkube
      group: org.eclipse.jkube.integration.tests.gradle
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          app.openshift.io/vcs-ref: "@ignore@"
          keyinall: valueinall
          jkube.io/git-branch: "@ignore@"
          keyindeployment: valueindeployment
          keyinpodtemplate: valueinpodtemplate
          jkube.io/git-url: "@ignore@"
          app.openshift.io/vcs-uri: "@ignore@"
          jkube.io/git-commit: "@ignore@"
        labels:
          keyinpodtemplate: valueinpodtemplate
          keyinall: valueinall
          app: metadata
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: repository/metadata:latest
          imagePullPolicy: IfNotPresent
          name: repository-metadata
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - repository-metadata
        from:
          kind: ImageStreamTag
          name: metadata:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      app.openshift.io/vcs-ref: "@ignore@"
      jkube.io/git-url: "@ignore@"
      app.openshift.io/vcs-uri: "@ignore@"
      jkube.io/git-commit: "@ignore@"
      keyinall: valueinall
      keyinroute: valueinroute
      jkube.io/git-branch: "@ignore@"
    labels:
      keyinall: valueinall
      keyinroute: valueinroute
      app: metadata
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: metadata
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: metadata
