ifeval::["{plugin-type}" == "maven"]
[[jkube:helm-push]]
== *{goal-prefix}:helm-push*
endif::[]
ifeval::["{plugin-type}" == "gradle"]
[[jkubeHelmPush]]
=== *{task-prefix}HelmPush*
endif::[]

This feature allows you to upload your Eclipse JKube-generated
https://helm.sh/docs/topics/charts[Helm charts]
to one of the supported repositories: Artifactory, Chartmuseum, Nexus, and OCI.

ifeval::["{plugin-type}" == "maven"]
include::maven/_mvn_helm_push.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_gradle_helm_push.adoc[]
endif::[]

The configuration is defined in a `helm` section within the plugin's configuration:

ifeval::["{plugin-type}" == "maven"]
include::maven/_example_helm_push_config.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_example_helm_push_config.adoc[]
endif::[]

ifeval::["{plugin-type}" == "maven"]
You can provide helm repository authentication credentials either via properties or using environment variables. It's also possible to specify credentials in maven settings as well. You just
need to add a server entry for your repo like this:

[#helm-repository-authentication-credentials-in-settings-xml]
.Helm Repository Authentication credentials in settings.xml
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>snapshot-repo-id</id>
      <username>admin</username>
      <password>secret</password>
    </server>
  </servers>

</settings>
----

If you have encrypted your password with a master password (as outlined in the http://maven.apache.org/guides/mini/guide-encryption.html[Maven Password Encryption guide]), your master password is encrypted somewhere in a file. By default this is `~/.m2/security-settings.xml`. If you've chosen another location, make sure to configure the `security` setting:
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<plugin>
  <configuration>
    <helm>
      <security>~/work/.m2/work-security-settings.xml</security>
      ...
    </helm>
  </configuration>
</plugin>
----
endif::[]


This configuration section knows the following sub-elements in order to configure your Helm chart.

.Helm configuration
[cols="1,5,1"]
|===
| Element | Description | Property

| *stableRepository*
| The configuration of the stable helm repository (see Helm stable repository configuration).
|

| *snapshotRepository*
| The configuration of the snapshot helm repository (see Helm repository configuration).
|

|===

.Helm stable repository configuration
[cols="1,5,1"]
|===
| Element | Description | Property

| *name*
| The name (id) of the server configuration. It can select the maven server by this ID.
| `jkube.helm.stableRepository.name`

| *url*
| The url of the server.
| `jkube.helm.stableRepository.url`

| *username*
| The username of the repository. Optional. If a maven server ID is specified, the username is taken from there.
| `jkube.helm.stableRepository.username`

| *password*
| The password of the repository. Optional. If a maven server ID is specified, the password is taken from there.
| `jkube.helm.stableRepository.password`

| *type*
| The type of the repository. One of ARTIFACTORY, NEXUS, CHARTMUSEUM, OCI
| `jkube.helm.stableRepository.type`

|
|===

.Helm snapshot repository configuration
[cols="1,5,1"]
|===
| Element | Description | Property

| *name*
| The name (id) of the server configuration. It can select the maven server by this ID.
| `jkube.helm.snapshotRepository.name`

| *url*
| The url of the server.
| `jkube.helm.snapshotRepository.url`

| *username*
| The username of the repository. Optional. If a maven server ID is specified, the username is taken from there.
| `jkube.helm.snapshotRepository.username`

| *password*
| The password of the repository. Optional. If a maven server ID is specified, the password is taken from there.
| `jkube.helm.snapshotRepository.password`

| *type*
| The type of the repository. One of ARTIFACTORY, NEXUS, CHARTMUSEUM
| `jkube.helm.snapshotRepository.type`

|
|===


ifeval::["{plugin-type}" == "maven"]
To add the `helm-push` goal to your project so that it is automatically executed just add the `helm-push` goal to the `executions`
section of the `{plugin}` section of your `pom.xml`.

include::maven/_jkube_resource_helm_push_execution.adoc[]
endif::[]
