ifeval::["{plugin-type}" == "maven"]
[[jkube:helm]]
== *{goal-prefix}:helm*
endif::[]
ifeval::["{plugin-type}" == "gradle"]
[[jkubeHelm]]
=== *{task-prefix}Helm*
endif::[]

This feature allows you to create https://helm.sh/docs/topics/charts[Helm charts] from the Kubernetes resources Eclipse JKube generates for your project.
You can then use the generated charts to leverage https://github.com/helm/helm[Helm]'s capabilities to install, update, or delete your app in Kubernetes.

ifeval::["{plugin-type}" == "maven"]
include::maven/_mvn_helm.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_gradle_helm.adoc[]
endif::[]

There are multiple ways to configure the generated Helm Chart:

* By providing a `Chart.helm.yaml` fragment in `src/main/jkube` directory.
* Through the `helm` section in the {plugin} {plugin-configuration-type} configuration.

When using the fragment approach, you simply need to create a `Chart.helm.yaml` file in the `src/main/jkube` directory with the fields you want to override.
JKube will take care of merging this fragment with the opinionated and configured defaults.

The {plugin-configuration-type} configuration is defined in a `helm` section within the plugin's configuration:

ifeval::["{plugin-type}" == "maven"]
include::maven/_example_helm_config.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_example_helm_config.adoc[]
endif::[]

This configuration section knows the following sub-elements in order to configure your Helm chart.

.Helm configuration
[cols="1,5,1"]
|===
| Element | Description | Property

| *apiVersion*
| The apiVersion of Chart.yaml schema, defaults to v1.
| `jkube.helm.apiVersion`

| *chart*
| The Chart name.
ifeval::["{plugin-type}" == "maven"]

Defaults to `${project.artifactId}`.
endif::[]
| `jkube.helm.chart`

| *version*
| The Chart SemVer version.
ifeval::["{plugin-type}" == "maven"]

Defaults to `${project.version}`.
endif::[]
| `jkube.helm.version`

| *description*
| The Chart single-sentence description.
ifeval::["{plugin-type}" == "maven"]

Defaults to `${project.description}`.
endif::[]
| `jkube.helm.description`

| *home*
| The Chart URL for this project's home page.
ifeval::["{plugin-type}" == "maven"]

Defaults to `${project.url}`.
endif::[]
| `jkube.helm.home`

| *sources*
| The Chart list of URLs to source code for this project.
ifeval::["{plugin-type}" == "maven"]

Defaults to the list of `${project.scm.url}`.
endif::[]
|

| *<<helm-maintainers, maintainers>>*
| The Chart list of maintainers (name+email).
ifeval::["{plugin-type}" == "maven"]

Defaults to the list of `${project.developers.name}:${project.developers.name}`.
endif::[]
|

| *icon*
| The Chart URL to an SVG or PNG image to be used as an icon, default is extracted from the kubernetes manifest
(`kubernetes.yml`) `jkube.eclipse.org/iconUrl` annotation if not provided.
| `jkube.helm.icon`

| *appVersion*
| The version of the application that Chart contains.
ifeval::["{plugin-type}" == "maven"]

Defaults to `${project.version}`.
endif::[]
| `jkube.helm.appVersion`

| *keywords*
| Comma separated list of keywords to add to the chart.
|

| *engine*
| The template engine to use.
|

| *additionalFiles*
| The list of additional files to be included in the Chart archive. Any file named `README` or `LICENSE` or `values.schema.json` will *always*
be included by default.
|

| *type* / *types*
| Platform for which to generate the chart. By default this is `kubernetes`, but can be also `openshift` for using
OpenShift specific resources in the chart. You can also add both values as a comma separated list.

  _Please note that there is no OpenShift support yet for charts, so this is experimental._
| `jkube.helm.type`

| *sourceDir*
|
ifeval::["{plugin-type}" == "maven"]
Where to find the resource descriptors generated with `{goal-prefix}:resource`.

By default, this is `${basedir}/target/classes/META-INF/jkube., which is also the output directory used by `{goal-prefix}:resource`.
endif::[]
ifeval::["{plugin-type}" == "gradle"]
Where to find the resource descriptors generated with `{task-prefix}Resource`.

By default, this is `${basedir}/build/classes/java/main/classes/META-INF/jkube`, which is also the output directory used by `{task-prefix}Resource`.
endif::[]
| `jkube.helm.sourceDir`

| *outputDir*
|
ifeval::["{plugin-type}" == "maven"]
Where to create the Helm chart, which is `${basedir}/target/jkube/helm/${chartName}/kubernetes` by default for Kubernetes
and `${basedir}/target/jkube/helm/${chartName}/openshift` for OpenShift.
endif::[]
ifeval::["{plugin-type}" == "gradle"]
Where to create the Helm chart, which is `${basedir}/build/jkube/helm/${chartName}/kubernetes` by default for Kubernetes
and `${basedir}/build/jkube/helms/${chartName}/openshift` for OpenShift.
endif::[]
| `jkube.helm.outputDir`

| *tarballOutputDir*
| Where to create the Helm chart archive, which is same as `outputDir` if not provided.
| `jkube.helm.tarballOutputDir`

| *tarFileClassifier*
| A string at the end of Helm archive filename as a classifier.

Defaults to empty string.
| `jkube.helm.tarFileClassifier`

| *chartExtension*
| The Helm chart file extension (`tgz`, `tar.bz`, `tar.bzip2`, `tar.bz2`), default value is `tar.gz` if not provided.
| `jkube.helm.chartExtension`

ifeval::["{plugin-type}" == "maven"]
| *security*
| The Maven security dispatcher configuration file. If you use the default security dispatcher, you need to point this to the file containing your master password. If you followed the http://maven.apache.org/guides/mini/guide-encryption.html[Maven Password Encryption guide], this is `${user.home}/.m2/settings-security.xml`, so that is what this setting defaults to when you do not set it explicitly.
|
endif::[]

| *<<helm-dependencies, dependencies>>*
| The list of dependencies for this chart.
|

| *<<helm-parameters, parameters>>*
| The list of parameters to interpolate the Chart templates from the provided Fragments.

  These parameters can represent variables, in this case the values are used to generate
  the `values.yaml` file. The fragment placeholders will be replaced with a `.Values` variable.

  The parameters can also represent a Golang expression
|

|===

[[helm-maintainers]]
.Helm Configuration - Maintainer
[cols="1,5"]
|===
| Element | Description

| *name*
| The maintainer's name or organization.

| *email*
| The maintainer's contact email address.

| *url*
| The maintainer's URL address.

|===

[[helm-dependencies]]
.Helm Configuration - Dependency
[cols="1,5"]
|===
| Element | Description

| *name*
| The name of the chart dependency.

| *version*
| Semantic version or version range for the dependency.

| *repository*
| URL pointing to a chart repository.

| *condition*
| Optional reference to a boolean value that toggles the inclusion of the dependency.  IE `subchart.enabled`. For more information see helm https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies[documentation].

| *alias*
| Optional reference to the map that will be passed as the value scope for the subchart. For more information see helm https://helm.sh/docs/topics/charts/#alias-field-in-dependencies[documentation].

|===

[[helm-parameters]]
.Helm Configuration - Parameters
[cols="1,5"]
|===
| Element | Description

| *name*
| The name of the interpolatable parameter. Will be used to replace placeholders
(`$\{name}`) in the provided YAML fragments. And to generate the `values.yaml` file.

| *required*
| Set to true if this is a required value (when used to generate values).

| *value*
| In case we are generating a `.Values` variable, the default value.

  In case the placeholder has to be replaced by an expression, the Golang expression
  e.g. `{{ .Chart.Name \| upper }}`.

|===

// TODO: Remove if Once header depth is aligned in both plugins
ifeval::["{plugin-type}" == "maven"]
=== Helm-specific fragments
endif::[]
ifeval::["{plugin-type}" == "gradle"]
==== Helm-specific fragments
endif::[]

In addition to the standard Kubernetes <<introduction-examples-resource-fragments, resource fragments>>, you can also provide fragments for Helm `Chart.yaml` and `values.yaml` files.

For the `Chart.yaml` file you can provide a `Chart.helm.yaml` fragment in the `src/main/jkube` directory.

For the `values.yaml` file you can provide a `values.helm.yaml` fragment in the `src/main/jkube` directory.

These fragments will be merged with the opinionated and configured defaults.
The values provided in the fragments will override any of the generated default values taking precedence over them.

// TODO: Remove if Once header depth is aligned in both plugins
ifeval::["{plugin-type}" == "maven"]
=== Installing the generated Helm chart
endif::[]
ifeval::["{plugin-type}" == "gradle"]
==== Installing the generated Helm chart
endif::[]

In a next step you can install this via the https://github.com/helm/helm/releases[helm command line tool] as follows:

ifeval::["{plugin-type}" == "maven"]
include::maven/_helm_install.adoc[]

In addition, this goal will also create a tar-archive below `${basedir}/target` which contains the chart with its template.
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_helm_install.adoc[]

In addition, this task will also create a tar-archive below `outputDir` which contains the chart with its template.
endif::[]


ifeval::["{plugin-type}" == "maven"]
include::maven/_jkube_helm_maven_execution.adoc[]
include::_jkube_helm_multimodule.adoc[]
endif::[]

