
[[jkube-healthcheck-spring-boot]]
==== jkube-healthcheck-spring-boot

This enricher adds kubernetes readiness and liveness probes with Spring Boot. This requires the following dependency
has been enabled in Spring Boot

ifeval::["{plugin-type}" == "maven"]
include::maven/_actuator_dependency.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_actuator_dependency.adoc[]
endif::[]

The enricher will try to discover the settings from the `application.properties` / `application.yaml` Spring Boot configuration file.

The port number is read from the `management.port` option, and will use the default value of `8080`
The scheme will use HTTPS if `server.ssl.key-store` option is in use, and fallback to use `HTTP` otherwise.

The enricher will use the following settings by default:

* `readinessProbeInitialDelaySeconds` : `10`
* `readinessProbePeriodSeconds` : _<kubernetes-default>_
* `livenessProbeInitialDelaySeconds` : `180`
* `livenessProbePeriodSeconds` : _<kubernetes-default>_
* `timeoutSeconds` : _<kubernetes-default>_
* `failureThreshold`: `3`
* `successThreshold`: `1`

These values can be configured by the enricher in the `{plugin}` configuration as shown below:

ifeval::["{plugin-type}" == "maven"]
include::maven/_configuration.adoc[]
endif::[]
ifeval::["{plugin-type}" == "gradle"]
include::gradle/_configuration.adoc[]
endif::[]
