---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-url: "@ignore@"
      jkube.eclipse.org/git-commit: "@ignore@"
      jkube.eclipse.org/git-branch: "@ignore@"
    labels:
      app: debug-mode
      provider: jkube
      version: "@ignore@"
      group: org.eclipse.jkube.integration.tests.gradle
    name: debug-mode
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: debug-mode
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-url: "@ignore@"
          jkube.eclipse.org/git-commit: "@ignore@"
          jkube.eclipse.org/git-branch: "@ignore@"
        labels:
          app: debug-mode
          provider: jkube
          version: "@ignore@"
          group: org.eclipse.jkube.integration.tests.gradle
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_ENABLE_DEBUG
            value: "true"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: repository/debug-mode:latest
          imagePullPolicy: IfNotPresent
          name: repository-debug-mode
          ports:
            - containerPort: 5005
              name: debug
          securityContext:
            privileged: false
