---
apiVersion: v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        app.openshift.io/vcs-ref: "@ignore@"
        jkube.io/git-url: "@ignore@"
        app.openshift.io/vcs-uri: "@ignore@"
        jkube.io/git-commit: "@ignore@"
        jkube.io/git-branch: "@ignore@"
      labels:
        app: debug-mode
        provider: jkube
        version: "@ignore@"
        group: org.eclipse.jkube.integration.tests.gradle
      name: debug-mode
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: debug-mode
        provider: jkube
        group: org.eclipse.jkube.integration.tests.gradle
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          annotations:
            app.openshift.io/vcs-ref: "@ignore@"
            jkube.io/git-url: "@ignore@"
            app.openshift.io/vcs-uri: "@ignore@"
            jkube.io/git-commit: "@ignore@"
            jkube.io/git-branch: "@ignore@"
          labels:
            app: debug-mode
            provider: jkube
            version: "@ignore@"
            group: org.eclipse.jkube.integration.tests.gradle
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: JAVA_ENABLE_DEBUG
                  value: "true"
              image: repository/debug-mode:latest
              imagePullPolicy: IfNotPresent
              name: repository-debug-mode
              ports:
                - containerPort: 5005
                  name: debug
              securityContext:
                privileged: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - repository-debug-mode
            from:
              kind: ImageStreamTag
              name: debug-mode:latest
          type: ImageChange